'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import MasterManager from '@/components/master-manager'
type Row=Record<string,unknown>
type Module='dashboard'|'masters'|'purchases'|'inventory'|'production'|'orders'|'sales'|'payments'|'reports'
const masterTables=['items','suppliers','customers','units','categories','sub_agents'] as const
function useRows(table:string){const[rows,setRows]=useState<Row[]>([]);const[error,setError]=useState('');useEffect(()=>{createClient().from(table).select('*').limit(50).then(({data,error})=>{if(error)setError(error.message);else setRows((data??[])as Row[])})},[table]);return{rows,error}}
function Table({rows}:{rows:Row[]}){if(!rows.length)return <p className="empty-state">No records yet.</p>;const keys=Object.keys(rows[0]).filter(k=>!['id','created_at','updated_at'].includes(k)).slice(0,7);return <div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{keys.map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="console-panel"><div className="panel-heading"><h2>{title}</h2></div>{children}</div>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <section className="page-panel"><div className="section-label">Mane Masala</div><h1>{title}</h1><p className="page-intro">Connected to the persistent Mane Masala database.</p>{children}</section>}
export default function BusinessConsole({module}:{module:Module}){if(module==='masters')return <Masters/>;if(module==='purchases')return <List title="Purchases" table="purchases"/>;if(module==='inventory')return <List title="Inventory" table="v_inventory_current"/>;if(module==='production')return <Dual title="Production" a="recipes" b="production_batches" al="Recipes" bl="Production batches"/>;if(module==='orders')return <List title="Orders" table="orders"/>;if(module==='sales')return <Dual title="Sales & Invoices" a="sales" b="invoices" al="Sales" bl="Invoices"/>;if(module==='payments')return <Dual title="Payments" a="supplier_payments" b="customer_payments" al="Supplier payments" bl="Customer payments"/>;if(module==='reports')return <Dual title="Reports" a="v_supplier_outstanding" b="v_customer_outstanding" al="Supplier outstanding" bl="Customer outstanding"/>;return <Dashboard/>}
function List({title,table}:{title:string;table:string}){const{rows,error}=useRows(table);return <Page title={title}><Panel title={title}>{error?<p className="form-status form-status-error">{error}</p>:<Table rows={rows}/>}</Panel></Page>}
function Dual({title,a,b,al,bl}:{title:string;a:string;b:string;al:string;bl:string}){const x=useRows(a),y=useRows(b);return <Page title={title}><div className="console-grid"><Panel title={al}>{x.error?<p className="form-status form-status-error">{x.error}</p>:<Table rows={x.rows}/>}</Panel><Panel title={bl}>{y.error?<p className="form-status form-status-error">{y.error}</p>:<Table rows={y.rows}/>}</Panel></Page>}
function Masters(){const[table,setTable]=useState<(typeof masterTables)[number]>('items');return <Page title="Masters & Settings"><div className="master-tabs">{masterTables.map(t=><button key={t} className={table===t?'tab-active':''} onClick={()=>setTable(t)}>{t.replaceAll('_',' ')}</button>)}</div><MasterManager table={table}/></Page>}
function Dashboard(){const[n,setN]=useState<Record<string,number>>({});useEffect(()=>{const sb=createClient();Promise.all(['items','suppliers','customers','purchases','orders'].map(t=>sb.from(t).select('*',{count:'exact',head:true}))).then(r=>setN(Object.fromEntries(['items','suppliers','customers','purchases','orders'].map((k,i)=>[k,r[i].count??0]))))},[]);return <Page title="Dashboard"><div className="dashboard-grid">{Object.entries(n).map(([k,v])=><div className="dashboard-card" key={k}><span>{k}</span><strong>{v}</strong><small>Live database count</small></div>)}</div></Page>}
