'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import DataTable from '@/components/data-table'

type Row = Record<string, any>
type Module = 'inventory' | 'production' | 'orders' | 'sales' | 'payments'
const sb = () => createClient()
const today = () => new Date().toISOString().slice(0, 10)
const t = (v: any) => String(v ?? '')

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="modal-backdrop"><div className="modal-card"><div className="modal-header"><h3>{title}</h3><button className="secondary-button" onClick={onClose}>Close</button></div>{children}</div></div>
}
function Status({ message, error = false }: { message: string; error?: boolean }) { return message ? <p className={`form-status${error ? ' form-status-error' : ''}`} role="alert">{message}</p> : null }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Page({ title, actionLabel, onAction, children }: { title: string; actionLabel: string; onAction: () => void; children: React.ReactNode }) {
  return <section className="page-panel"><div className="section-label">Mane Masala</div><div className="master-header"><div><h1>{title}</h1><p className="page-intro">Use one clear business action at a time. Lists support search, sorting and pagination.</p></div><button className="primary-button" onClick={onAction}>{actionLabel}</button></div>{children}</section>
}
function Select({ value, onChange, children }: { value: string; onChange: (v: string) => void; children: React.ReactNode }) { return <select value={value} onChange={e => onChange(e.target.value)}>{children}</select> }

function useRows(table: string, refresh = 0) {
  const [rows, setRows] = useState<Row[]>([])
  useEffect(() => { let live = true; void sb().from(table).select('*').limit(500).then(({ data }) => { if (live) setRows((data ?? []) as Row[]) }); return () => { live = false } }, [table, refresh])
  return rows
}

function Orders() {
  type Line = { itemId: string; quantity: string; rate: string }
  type Draft = { party: 'direct'|'sub_agent'; customerId: string; subAgentId: string; endMode: 'existing'|'named'|'anonymous'; endCustomerId: string; endName: string; endPhone: string; source: string; date: string; dispatchDate: string; advance: string; requests: string; notes: string; lines: Line[] }
  const customers = useRows('customers'), subAgents = useRows('sub_agents'), items = useRows('items')
  const [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [msg, setMsg] = useState(''), [error, setError] = useState(false)
  const empty = (): Draft => ({ party: 'direct', customerId: '', subAgentId: '', endMode: 'named', endCustomerId: '', endName: '', endPhone: '', source: 'whatsapp', date: today(), dispatchDate: '', advance: '', requests: '', notes: '', lines: [{ itemId: '', quantity: '', rate: '' }] })
  const [drafts, setDrafts] = useState<Draft[]>([empty()])
  const addOrder = () => setDrafts(v => [...v, empty()])
  const removeOrder = (index: number) => setDrafts(v => v.length === 1 ? v : v.filter((_, i) => i !== index))
  const patch = (oi: number, key: keyof Draft, value: any) => setDrafts(v => v.map((d, i) => i === oi ? { ...d, [key]: value } : d))
  const patchLine = (oi: number, li: number, key: keyof Line, value: string) => setDrafts(v => v.map((d, i) => i === oi ? { ...d, lines: d.lines.map((l, j) => j === li ? { ...l, [key]: value } : l) } : d))
  const addLine = (oi: number) => setDrafts(v => v.map((d, i) => i === oi ? { ...d, lines: [...d.lines, { itemId: '', quantity: '', rate: '' }] } : d))
  const save = async () => {
    setSaving(true); setError(false); setMsg('')
    for (let oi = 0; oi < drafts.length; oi++) {
      const d = drafts[oi]
      if (!d.customerId) { setError(true); setMsg(`Order ${oi + 1}: select the billing customer.`); setSaving(false); return }
      if (d.party === 'sub_agent' && !d.subAgentId) { setError(true); setMsg(`Order ${oi + 1}: select the Sub-Agent.`); setSaving(false); return }
      if (d.party === 'sub_agent' && d.endMode === 'existing' && !d.endCustomerId) { setError(true); setMsg(`Order ${oi + 1}: select the end customer.`); setSaving(false); return }
      if (d.party === 'sub_agent' && d.endMode === 'named' && !d.endName.trim()) { setError(true); setMsg(`Order ${oi + 1}: enter the end customer name or choose Anonymous.`); setSaving(false); return }
      if (!d.lines.some(l => l.itemId && Number(l.quantity) > 0)) { setError(true); setMsg(`Order ${oi + 1}: add at least one item line.`); setSaving(false); return }
    }
    const payload = drafts.map(d => ({ customer_id: d.customerId, order_party_type: d.party, sub_agent_id: d.party === 'sub_agent' ? d.subAgentId : null, end_customer_customer_id: d.party === 'sub_agent' && d.endMode === 'existing' ? d.endCustomerId : null, end_customer_name: d.party === 'sub_agent' && d.endMode === 'named' ? d.endName.trim() : null, end_customer_phone: d.party === 'sub_agent' ? d.endPhone.trim() || null : null, end_customer_is_anonymous: d.party === 'sub_agent' && d.endMode === 'anonymous', order_date: d.date, estimated_dispatch_date: d.dispatchDate || null, source: d.source, advance_amount: Number(d.advance || 0), requests: d.requests.trim() || null, notes: d.notes.trim() || null, lines: d.lines.filter(l => l.itemId && Number(l.quantity) > 0).map(l => { const it = items.find(x => t(x.id) === l.itemId); return { item_id: l.itemId, ordered_quantity: Number(l.quantity), unit_id: it?.base_unit_id, selling_rate: Number(l.rate || 0) } }) }))
    const { error: e } = await sb().rpc('create_order_entry_session', { p_orders: payload })
    if (e) { setError(true); setMsg(e.message); setSaving(false); return }
    setMsg(`${drafts.length} separate order${drafts.length === 1 ? '' : 's'} saved. Each has its own permanent Order record.`); setDrafts([empty()]); setSaving(false)
  }
  return <Page title="Orders" actionLabel="+ Create Orders" onAction={() => { setMsg(''); setError(false); setOpen(true) }}>
    <div className="console-panel"><div className="panel-heading"><h2>Order entry</h2></div><p className="muted">One customer can order many items. In one entry session you can capture several separate customers; the system keeps each order as a separate transaction.</p></div>
    {open && <Modal title="Create customer orders" onClose={() => setOpen(false)}>
      {drafts.map((d, oi) => <div className="console-panel" key={oi} style={{ marginBottom: 16 }}><div className="panel-heading"><h2>Order {oi + 1}</h2><button className="secondary-button" onClick={() => removeOrder(oi)} disabled={drafts.length === 1}>Remove order</button></div>
        <div className="form-grid"><Field label="Order type"><Select value={d.party} onChange={v => patch(oi, 'party', v)}><option value="direct">Direct customer</option><option value="sub_agent">Through Sub-Agent</option></Select></Field><Field label="Billing customer"><Select value={d.customerId} onChange={v => patch(oi, 'customerId', v)}><option value="">Select billing customer</option>{customers.filter(x => x.is_active !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.name)}</option>)}</Select></Field>{d.party === 'sub_agent' && <Field label="Sub-Agent"><Select value={d.subAgentId} onChange={v => patch(oi, 'subAgentId', v)}><option value="">Select Sub-Agent</option>{subAgents.filter(x => x.is_active !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.name)}</option>)}</Select></Field>}</div>
        {d.party === 'sub_agent' && <div className="form-grid"><Field label="End customer"><Select value={d.endMode} onChange={v => patch(oi, 'endMode', v)}><option value="existing">Existing customer</option><option value="named">Named but not registered</option><option value="anonymous">Anonymous customer</option></Select></Field>{d.endMode === 'existing' && <Field label="End customer record"><Select value={d.endCustomerId} onChange={v => patch(oi, 'endCustomerId', v)}><option value="">Select end customer</option>{customers.map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.name)}</option>)}</Select></Field>}{d.endMode === 'named' && <Field label="End customer name"><input value={d.endName} onChange={e => patch(oi, 'endName', e.target.value)} placeholder="Name" /></Field>}<Field label="End customer phone"><input value={d.endPhone} onChange={e => patch(oi, 'endPhone', e.target.value)} placeholder="Optional" /></Field></div>}
        <div className="form-grid"><Field label="Order date"><input type="date" value={d.date} onChange={e => patch(oi, 'date', e.target.value)} /></Field><Field label="Estimated dispatch date"><input type="date" value={d.dispatchDate} onChange={e => patch(oi, 'dispatchDate', e.target.value)} /></Field><Field label="Order source"><Select value={d.source} onChange={v => patch(oi, 'source', v)}><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="phone">Phone</option><option value="social_media">Social Media</option><option value="walk_in">Walk-in</option><option value="online_marketplace">Online Marketplace</option></Select></Field><Field label="Advance amount"><input type="number" min="0" step="0.01" value={d.advance} onChange={e => patch(oi, 'advance', e.target.value)} /></Field></div>
        <h3>Items on this order</h3><div className="purchase-lines">{d.lines.map((l, li) => <div className="purchase-line" key={li}><Field label="Item"><Select value={l.itemId} onChange={v => patchLine(oi, li, 'itemId', v)}><option value="">Select item</option>{items.filter(x => x.is_active !== false && x.can_be_sold !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.item_code)} — {t(x.name)}</option>)}</Select></Field><Field label="Quantity"><input type="number" min="0" step="0.001" value={l.quantity} onChange={e => patchLine(oi, li, 'quantity', e.target.value)} /></Field><Field label="Selling rate"><input type="number" min="0" step="0.01" value={l.rate} onChange={e => patchLine(oi, li, 'rate', e.target.value)} /></Field></div>)}</div><button className="add-row-button" type="button" onClick={() => addLine(oi)}>＋ Add item row</button>
        <div className="form-grid"><Field label="Requests"><textarea value={d.requests} onChange={e => patch(oi, 'requests', e.target.value)} placeholder="Customer requests" /></Field><Field label="Notes"><textarea value={d.notes} onChange={e => patch(oi, 'notes', e.target.value)} placeholder="Internal notes" /></Field></div>
      </div>)}
      <button className="add-row-button" onClick={addOrder}>＋ Add another customer order</button><div className="purchase-actions"><button className="primary-button" onClick={save} disabled={saving}>{saving ? 'Saving...' : 'Save all orders'}</button></div><Status message={msg} error={error}/>
    </Modal>}
    <div style={{ marginTop: 18 }}><DataTable table="orders"/></div>
  </Page>
}

function Inventory() {
  const items = useRows('items'), units = useRows('units'), [open, setOpen] = useState<'out'|'adjust'|null>(null), [iid, setIid] = useState(''), [qty, setQty] = useState(''), [unit, setUnit] = useState(''), [reason, setReason] = useState('damage'), [notes, setNotes] = useState(''), [delta, setDelta] = useState(''), [msg, setMsg] = useState(''), [error, setError] = useState(false)
  const selected = items.find(x => t(x.id) === iid)
  const submit = async () => { setError(false); setMsg(''); if (!iid || !unit) { setError(true); setMsg('Item and unit are required.'); return } const amount = open === 'out' ? -Number(qty) : Number(delta); if (!amount) { setError(true); setMsg('Quantity must be greater than zero.'); return } const rpc = open === 'out' ? 'record_stock_out' : 'record_stock_adjustment'; const args = open === 'out' ? { p_item_id: iid, p_quantity: Number(qty), p_unit_id: unit, p_stock_out_date: today(), p_reason: reason, p_notes: notes || null } : { p_item_id: iid, p_quantity_delta: amount, p_unit_id: unit, p_adjustment_date: today(), p_reason: reason, p_notes: notes || null }; const { error: e } = await sb().rpc(rpc, args); if (e) { setError(true); setMsg(e.message); return } setMsg(open === 'out' ? 'Stock out recorded using FIFO.' : 'Stock adjustment recorded.'); setOpen(null) }
  return <Page title="Inventory" actionLabel="+ Stock Action" onAction={() => { setOpen('out'); setMsg(''); setError(false) }}><div className="console-panel"><div className="panel-heading"><h2>Stock controls</h2></div><div className="action-row"><button className="secondary-button" onClick={() => setOpen('out')}>Stock Out</button><button className="secondary-button" onClick={() => setOpen('adjust')}>Stock Adjustment</button></div><p className="muted">Current stock is transaction-derived. Do not edit balances directly.</p></div>{open && <Modal title={open === 'out' ? 'Record Stock Out' : 'Record Stock Adjustment'} onClose={() => setOpen(null)}><div className="form-grid"><Field label="Item"><Select value={iid} onChange={setIid}><option value="">Select item</option>{items.filter(x => x.is_active !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.item_code)} — {t(x.name)}</option>)}</Select></Field><Field label="Unit"><Select value={unit} onChange={setUnit}><option value="">Select unit</option>{units.map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.name)} ({t(x.symbol)})</option>)}</Select></Field>{open === 'out' ? <Field label="Quantity"><input type="number" min="0" step="0.001" value={qty} onChange={e => setQty(e.target.value)} /></Field> : <Field label="Adjustment (+ adds / − removes)"><input type="number" step="0.001" value={delta} onChange={e => setDelta(e.target.value)} /></Field>}<Field label="Reason"><Select value={reason} onChange={setReason}><option value="damage">Damage</option><option value="expiry">Expiry</option><option value="sample">Sample</option><option value="wastage">Wastage</option><option value="personal_use">Personal use</option><option value="production">Production</option><option value="correction">Correction</option><option value="other">Other</option></Select></Field></div><Field label="Notes"><textarea value={notes} onChange={setNotes} /></Field>{selected && <p className="muted">Selected: {t(selected.item_code)} — {t(selected.name)}</p>}<div className="purchase-actions"><button className="primary-button" onClick={submit}>{open === 'out' ? 'Record Stock Out' : 'Record Adjustment'}</button></div><Status message={msg} error={error}/></Modal>}<div style={{ marginTop: 18 }}><DataTable table="v_inventory_current"/></div></Page>
}

function Production() {
  const items = useRows('items'), units = useRows('units'), batches = useRows('production_batches'), [open, setOpen] = useState<'create'|'complete'|null>(null), [output, setOutput] = useState(''), [planned, setPlanned] = useState(''), [unit, setUnit] = useState(''), [date, setDate] = useState(today()), [batchId, setBatchId] = useState(''), [actual, setActual] = useState(''), [ingredient, setIngredient] = useState(''), [consumed, setConsumed] = useState(''), [msg, setMsg] = useState(''), [error, setError] = useState(false)
  const create = async () => { setError(false); setMsg(''); if (!output || !unit || !planned) { setError(true); setMsg('Output, planned quantity and unit are required.'); return } const { data, error: e } = await sb().from('production_batches').insert({ output_item_id: output, planned_output_quantity: Number(planned), output_unit_id: unit, production_date: date, status: 'planned', wife_approval_status: 'pending' }).select().single(); if (e) { setError(true); setMsg(e.message); return } setBatchId(t(data.id)); setMsg('Production batch created. It must be approved before completion.'); setOpen(null) }
  const approve = async () => { if (!batchId) { setError(true); setMsg('Select a production batch.'); return } const { error: e } = await sb().from('production_batches').update({ wife_approval_status: 'approved', approved_at: new Date().toISOString() }).eq('id', batchId); if (e) { setError(true); setMsg(e.message); return } setMsg('Production batch approved.'); }
  const complete = async () => { if (!batchId || !ingredient || !consumed || !actual) { setError(true); setMsg('Batch, actual output and ingredient consumption are required.'); return } const ing = items.find(x => t(x.id) === ingredient), batch = batches.find(x => t(x.id) === batchId); if (!ing || !batch) { setError(true); setMsg('Batch or ingredient not found.'); return } const { error: e } = await sb().rpc('complete_production', { p_production_batch_id: batchId, p_consumptions: [{ ingredient_item_id: ingredient, actual_quantity: Number(consumed), unit_id: ing.base_unit_id }], p_outputs: [{ output_item_id: batch.output_item_id, quantity: Number(actual), unit_id: batch.output_unit_id, unit_cost: null }] }); if (e) { setError(true); setMsg(e.message); return } setMsg('Production completed and stock updated.'); setOpen(null) }
  return <Page title="Production" actionLabel="+ Create Production" onAction={() => { setOpen('create'); setMsg(''); setError(false) }}><div className="console-panel"><div className="panel-heading"><h2>Production controls</h2></div><div className="form-grid"><Field label="Production batch"><Select value={batchId} onChange={setBatchId}><option value="">Select batch</option>{batches.map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.business_code) || t(x.id).slice(0,8)} — {t(x.status)} — approval {t(x.wife_approval_status)}</option>)}</Select></Field><button className="secondary-button" onClick={approve}>Approve for production</button><button className="secondary-button" onClick={() => setOpen('complete')}>Complete production</button></div><Status message={msg} error={error}/></div>{open === 'create' && <Modal title="Create Production Batch" onClose={() => setOpen(null)}><div className="form-grid"><Field label="Output product"><Select value={output} onChange={setOutput}><option value="">Select output</option>{items.filter(x => x.can_be_sold !== false && x.is_active !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.item_code)} — {t(x.name)}</option>)}</Select></Field><Field label="Planned output"><input type="number" min="0" step="0.001" value={planned} onChange={e => setPlanned(e.target.value)} /></Field><Field label="Output unit"><Select value={unit} onChange={setUnit}><option value="">Select unit</option>{units.map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.name)} ({t(x.symbol)})</option>)}</Select></Field><Field label="Production date"><input type="date" value={date} onChange={e => setDate(e.target.value)} /></Field></div><div className="purchase-actions"><button className="primary-button" onClick={create}>Create batch</button></div><Status message={msg} error={error}/></Modal>}{open === 'complete' && <Modal title="Complete Production" onClose={() => setOpen(null)}><div className="form-grid"><Field label="Actual output"><input type="number" min="0" step="0.001" value={actual} onChange={e => setActual(e.target.value)} /></Field><Field label="Ingredient consumed"><Select value={ingredient} onChange={setIngredient}><option value="">Select ingredient</option>{items.filter(x => x.can_be_used_in_production !== false && x.is_active !== false).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.item_code)} — {t(x.name)}</option>)}</Select></Field><Field label="Actual quantity consumed"><input type="number" min="0" step="0.001" value={consumed} onChange={e => setConsumed(e.target.value)} /></Field></div><p className="muted">Completion consumes the entered ingredient through FIFO and creates the actual output batch. The batch must already be wife-approved.</p><div className="purchase-actions"><button className="primary-button" onClick={complete}>Complete production</button></div><Status message={msg} error={error}/></Modal>}<div style={{ marginTop: 18 }}><DataTable table="production_batches"/></div></Page>
}

function Sales() {
  const orders = useRows('orders'), dispatches = useRows('dispatches'), [open, setOpen] = useState(false), [orderId, setOrderId] = useState(''), [dispatchId, setDispatchId] = useState(''), [msg, setMsg] = useState(''), [error, setError] = useState(false)
  const dispatch = async () => { setError(false); setMsg(''); if (!orderId) { setError(true); setMsg('Select an order for dispatch.'); return } const { data: lines, error: le } = await sb().from('order_lines').select('id,ordered_quantity,dispatched_quantity').eq('order_id', orderId); if (le || !lines?.length) { setError(true); setMsg(le?.message ?? 'No order lines.'); return } const p_lines = lines.map(x => ({ order_line_id: x.id, quantity: Number(x.ordered_quantity) - Number(x.dispatched_quantity || 0) })).filter(x => x.quantity > 0); if (!p_lines.length) { setError(true); setMsg('Nothing remains to dispatch for this order.'); return } const { data, error: e } = await sb().rpc('dispatch_order', { p_order_id: orderId, p_dispatch_date: today(), p_method: 'other', p_lines }); if (e) { setError(true); setMsg(e.message); return } setDispatchId(t(data?.dispatch_id)); setMsg('Dispatch completed using FIFO. Select that dispatch to create the sale and invoice.'); }
  const invoice = async () => { setError(false); setMsg(''); if (!dispatchId) { setError(true); setMsg('Select the actual dispatch.'); return } const { error: e } = await sb().rpc('create_sale_invoice', { p_dispatch_id: dispatchId }); if (e) { setError(true); setMsg(e.message); return } setMsg('Sale and invoice created from the selected dispatch.'); }
  return <Page title="Sales & Invoices" actionLabel="+ Dispatch / Invoice" onAction={() => { setOpen(true); setMsg(''); setError(false) }}><div className="console-panel"><div className="panel-heading"><h2>Sales chain</h2></div><p className="muted">Dispatch owns the physical stock reduction. Sale and invoice are created only from the specific dispatch selected here.</p></div>{open && <Modal title="Dispatch then create Sale & Invoice" onClose={() => setOpen(false)}><div className="form-grid"><Field label="Order"><Select value={orderId} onChange={setOrderId}><option value="">Select ready order</option>{orders.filter(x => ['confirmed','production_planned','ready','partially_dispatched'].includes(t(x.status))).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.business_code) || t(x.id).slice(0,8)} — {t(x.status)}</option>)}</Select></Field><button className="secondary-button" onClick={dispatch}>Dispatch FIFO</button></div><div className="form-grid"><Field label="Actual dispatch"><Select value={dispatchId} onChange={setDispatchId}><option value="">Select dispatch</option>{dispatches.filter(x => t(x.order_id) === orderId).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.business_code) || t(x.id).slice(0,8)} — {t(x.dispatch_date)} — {t(x.status)}</option>)}</Select></Field><button className="primary-button" onClick={invoice}>Create Sale & Invoice</button></div><Status message={msg} error={error}/></Modal>}<div className="console-grid"><div className="console-panel"><div className="panel-heading"><h2>Dispatches</h2></div><DataTable table="dispatches"/></div><div className="console-panel"><div className="panel-heading"><h2>Invoices</h2></div><DataTable table="invoices"/></div></div></Page>
}

function Payments() {
  const invoices = useRows('invoices'), purchases = useRows('purchases'), customers = useRows('customers'), suppliers = useRows('suppliers'), [open, setOpen] = useState<'customer'|'supplier'|null>(null), [party, setParty] = useState(''), [refId, setRefId] = useState(''), [amount, setAmount] = useState(''), [method, setMethod] = useState('upi'), [upi, setUpi] = useState(''), [notes, setNotes] = useState(''), [msg, setMsg] = useState(''), [error, setError] = useState(false)
  const submit = async () => { setError(false); setMsg(''); if (!party || !amount || Number(amount) <= 0) { setError(true); setMsg('Party and a positive amount are required.'); return } const rpc = open === 'customer' ? 'record_customer_payment' : 'record_supplier_payment'; const args = open === 'customer' ? { p_customer_id: party, p_amount: Number(amount), p_payment_date: today(), p_method: method, p_invoice_id: refId || null, p_upi_reference: upi || null, p_notes: notes || null } : { p_supplier_id: party, p_amount: Number(amount), p_payment_date: today(), p_method: method, p_purchase_id: refId || null, p_upi_reference: upi || null, p_notes: notes || null }; const { error: e } = await sb().rpc(rpc, args); if (e) { setError(true); setMsg(e.message); return } setMsg(open === 'customer' ? 'Customer payment recorded.' : 'Supplier payment recorded.'); setOpen(null) }
  return <Page title="Payments" actionLabel="+ Record Payment" onAction={() => { setOpen('customer'); setParty(''); setRefId(''); setAmount(''); setMsg(''); setError(false) }}><div className="console-panel"><div className="panel-heading"><h2>Payment direction</h2></div><div className="action-row"><button className="secondary-button" onClick={() => setOpen('customer')}>Customer Payment (Money In)</button><button className="secondary-button" onClick={() => setOpen('supplier')}>Supplier Payment (Money Out)</button></div><p className="muted">The two directions are deliberately separate so a payment cannot accidentally be posted to the wrong side.</p></div>{open && <Modal title={open === 'customer' ? 'Record Customer Payment' : 'Record Supplier Payment'} onClose={() => setOpen(null)}><div className="form-grid"><Field label={open === 'customer' ? 'Customer' : 'Supplier'}><Select value={party} onChange={setParty}><option value="">Select</option>{(open === 'customer' ? customers : suppliers).map(x => <option key={t(x.id)} value={t(x.id)}>{t(open === 'customer' ? x.name : x.business_name)}</option>)}</Select></Field><Field label={open === 'customer' ? 'Invoice (optional)' : 'Purchase (optional)'}><Select value={refId} onChange={setRefId}><option value="">Leave as advance / unallocated</option>{(open === 'customer' ? invoices : purchases).map(x => <option key={t(x.id)} value={t(x.id)}>{t(x.business_code) || t(x.invoice_number) || t(x.id).slice(0,8)}</option>)}</Select></Field><Field label="Amount"><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Method"><Select value={method} onChange={setMethod}><option value="upi">UPI</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></Select></Field><Field label="UPI / payment reference"><input value={upi} onChange={e => setUpi(e.target.value)} placeholder="Optional" /></Field></div><Field label="Notes"><textarea value={notes} onChange={e => setNotes(e.target.value)} /></Field><div className="purchase-actions"><button className="primary-button" onClick={submit}>{open === 'customer' ? 'Record Customer Payment' : 'Record Supplier Payment'}</button></div><Status message={msg} error={error}/></Modal>}<div className="console-grid"><div className="console-panel"><div className="panel-heading"><h2>Customer payments</h2></div><DataTable table="customer_payments"/></div><div className="console-panel"><div className="panel-heading"><h2>Supplier payments</h2></div><DataTable table="supplier_payments"/></div></div></Page>
}

export default function OperationsConsole({ module }: { module: Module }) {
  if (module === 'orders') return <Orders />
  if (module === 'inventory') return <Inventory />
  if (module === 'production') return <Production />
  if (module === 'sales') return <Sales />
  return <Payments />
}
