'use client'

import { useEffect, useState, type ReactNode } from 'react'
import { createClient } from '@/lib/supabase/client'
import DataTable from '@/components/data-table'

type Row = Record<string, any>
type Module = 'inventory' | 'production' | 'orders' | 'sales' | 'payments'
const sb = () => createClient()
const today = () => new Date().toISOString().slice(0, 10)
const txt = (v: any) => String(v ?? '')

function Field({ label, children }: { label: string; children: ReactNode }) {
  return <label className="field"><span>{label}</span>{children}</label>
}
function Select({ value, onChange, children }: { value: string; onChange: (v: string) => void; children: ReactNode }) {
  return <select value={value} onChange={e => onChange(e.target.value)}>{children}</select>
}
function Status({ message, error = false }: { message: string; error?: boolean }) {
  return message ? <p className={`form-status${error ? ' form-status-error' : ''}`} role="alert">{message}</p> : null
}
function Modal({ title, close, children, wide = false }: { title: string; close: () => void; children: ReactNode; wide?: boolean }) {
  return <div className="modal-backdrop"><div className={`modal-card${wide ? ' purchase-modal' : ''}`}>
    <div className="modal-header"><h3>{title}</h3><button className="secondary-button" onClick={close}>Close</button></div>{children}
  </div></div>
}
function Page({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <section className="page-panel"><div className="section-label">Mane Masala</div><div className="master-header"><div><h1>{title}</h1><p className="page-intro">{description}</p></div>{children}</div></section>
}
function useRows(table: string) {
  const [rows, setRows] = useState<Row[]>([])
  const load = async () => { const { data } = await sb().from(table).select('*').limit(500); setRows(data ?? []) }
  useEffect(() => { void load() }, [table])
  return [rows, load] as const
}

function Orders() {
  const [customers] = useRows('customers'); const [agents] = useRows('sub_agents'); const [items] = useRows('items'); const [orders, reload] = useRows('v_orders_list')
  const [open, setOpen] = useState(false); const [drafts, setDrafts] = useState<any[]>([blankOrder()]); const [selected, setSelected] = useState<Row | null>(null); const [lines, setLines] = useState<any[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState(false); const [saving, setSaving] = useState(false)
  const fail = (m: string) => { setError(true); setMessage(m) }
  const patch = (i: number, key: string, value: any) => setDrafts(x => x.map((d, n) => n === i ? { ...d, [key]: value } : d))
  const patchLine = (oi: number, li: number, key: string, value: any) => setDrafts(x => x.map((d, n) => n === oi ? { ...d, lines: d.lines.map((l: any, j: number) => j === li ? { ...l, [key]: value } : l) } : d))
  const save = async () => {
    for (let i = 0; i < drafts.length; i++) { const d = drafts[i]; const billing = d.party === 'direct' ? d.customerId : agents.find(a => txt(a.id) === d.subAgentId)?.customer_id; if (!billing) return fail(`Order ${i + 1}: select the billing party.`); if (d.party === 'sub_agent' && d.endMode === 'existing' && !d.endCustomerId) return fail(`Order ${i + 1}: select the end customer.`); if (d.party === 'sub_agent' && d.endMode === 'named' && !d.endName.trim()) return fail(`Order ${i + 1}: enter the end customer name.`); if (!d.lines.some((l: any) => l.itemId && Number(l.quantity) > 0)) return fail(`Order ${i + 1}: add at least one item.`) }
    const payload = drafts.map(d => { const billing = d.party === 'direct' ? d.customerId : agents.find(a => txt(a.id) === d.subAgentId)?.customer_id; return { customer_id: billing, order_party_type: d.party, sub_agent_id: d.party === 'sub_agent' ? d.subAgentId : null, end_customer_customer_id: d.party === 'sub_agent' && d.endMode === 'existing' ? d.endCustomerId : null, end_customer_name: d.party === 'sub_agent' && d.endMode === 'named' ? d.endName.trim() : null, end_customer_phone: d.party === 'sub_agent' ? d.endPhone.trim() || null : null, end_customer_is_anonymous: d.party === 'sub_agent' && d.endMode === 'anonymous', order_date: d.date, estimated_dispatch_date: d.dispatchDate || null, source: d.source, advance_amount: Number(d.advance || 0), requests: d.requests.trim() || null, notes: d.notes.trim() || null, lines: d.lines.filter((l: any) => l.itemId && Number(l.quantity) > 0).map((l: any) => ({ item_id: l.itemId, ordered_quantity: Number(l.quantity), selling_rate: Number(l.rate || 0) })) } })
    setSaving(true); const { error: e } = await sb().rpc('create_order_entry_session', { p_orders: payload }); setSaving(false); if (e) return fail(e.message); setOpen(false); setDrafts([blankOrder()]); setError(false); setMessage(`${drafts.length} order${drafts.length === 1 ? '' : 's'} received. Prepare, reserve, then confirm.`); await reload()
  }
  const openPlan = async (order: Row) => {
    setSelected(order); setMessage(''); setError(false)
    const [{ data: ols }, { data: inv }, { data: rvs }] = await Promise.all([sb().from('order_lines').select('id,item_id,ordered_quantity,unit_id,selling_rate,reserved_quantity,produced_quantity,dispatched_quantity').eq('order_id', order.id), sb().from('v_inventory_current').select('*'), sb().from('recipe_versions').select('id,version_number,status,expected_output_quantity,output_unit_id,recipes!inner(output_item_id,name,status)').eq('status', 'active')])
    const map = new Map((inv ?? []).map(x => [txt(x.item_id), x])); const active = (rvs ?? []).filter((r: any) => r.recipes?.status === 'active')
    setLines((ols ?? []).map((l: any) => { const stock = map.get(txt(l.item_id)); const available = Math.max(0, Number(stock?.available_stock ?? 0)); const shortfall = Math.max(0, Number(l.ordered_quantity) - Math.min(Number(l.ordered_quantity), available)); const options = active.filter((r: any) => txt(r.recipes?.output_item_id) === txt(l.item_id)); const item = items.find(i => txt(i.id) === txt(l.item_id)); return { ...l, itemCode: item?.item_code, itemName: item?.name, available, shortfall, recipeVersionId: options.length === 1 ? txt(options[0].id) : '', recipeOptions: options } }))
  }
  const prepare = async () => { if (!selected) return; const selections = lines.filter(l => Number(l.shortfall) > 0).map(l => ({ order_line_id: l.id, recipe_version_id: l.recipeVersionId })); if (lines.some(l => Number(l.shortfall) > 0 && !l.recipeVersionId)) return fail('Select a recipe version for every item requiring production.'); const { error: e } = await sb().rpc('prepare_order_plan', { p_order_id: selected.id, p_recipe_selections: selections }); if (e) return fail(e.message); setError(false); setMessage('Plan prepared. Finished stock and production ingredients are reserved. Confirm the order next.'); await reload(); setSelected({ ...selected, status: 'production_planned' }) }
  const confirm = async () => { if (!selected) return; const { error: e } = await sb().rpc('confirm_order', { p_order_id: selected.id }); if (e) return fail(e.message); setError(false); setMessage('Order confirmed. Production can now start where required.'); await reload(); setSelected({ ...selected, status: 'confirmed' }) }
  return <Page title="Orders" description="Customer call → Order → production plan with recipe version → reserve inventory → confirm → production → dispatch → Sale & Invoice."><button className="primary-button" onClick={() => { setOpen(true); setMessage(''); setError(false) }}>+ Create Order</button>
    {open && <Modal title="Create customer orders" close={() => setOpen(false)} wide>{drafts.map((d, oi) => <div className="console-panel" key={oi} style={{ marginBottom: 16 }}><div className="panel-heading"><h2>Order {oi + 1}</h2><button className="secondary-button" disabled={drafts.length === 1} onClick={() => setDrafts(x => x.filter((_, n) => n !== oi))}>Remove</button></div>
      <div className="form-grid"><Field label="Order type"><Select value={d.party} onChange={v => patch(oi, 'party', v)}><option value="direct">Direct customer</option><option value="sub_agent">Through Sub-Agent</option></Select></Field>{d.party === 'direct' ? <Field label="Bill To — Customer"><Select value={d.customerId} onChange={v => patch(oi, 'customerId', v)}><option value="">Select customer</option>{customers.map(c => <option key={txt(c.id)} value={txt(c.id)}>{txt(c.name)} — {txt(c.business_code)}</option>)}</Select></Field> : <Field label="Bill To — Sub-Agent"><Select value={d.subAgentId} onChange={v => patch(oi, 'subAgentId', v)}><option value="">Select Sub-Agent</option>{agents.map(a => <option key={txt(a.id)} value={txt(a.id)}>{txt(a.name)} — {txt(a.business_code)}</option>)}</Select></Field>}<Field label="Order date"><input type="date" value={d.date} onChange={e => patch(oi, 'date', e.target.value)} /></Field><Field label="Estimated dispatch"><input type="date" value={d.dispatchDate} onChange={e => patch(oi, 'dispatchDate', e.target.value)} /></Field></div>
      {d.party === 'sub_agent' && <div className="form-grid"><Field label="End customer"><Select value={d.endMode} onChange={v => patch(oi, 'endMode', v)}><option value="existing">Existing customer</option><option value="named">Named but not registered</option><option value="anonymous">Anonymous</option></Select></Field>{d.endMode === 'existing' && <Field label="End customer record"><Select value={d.endCustomerId} onChange={v => patch(oi, 'endCustomerId', v)}><option value="">Select end customer</option>{customers.map(c => <option key={txt(c.id)} value={txt(c.id)}>{txt(c.name)}</option>)}</Select></Field>}{d.endMode === 'named' && <Field label="End customer name"><input value={d.endName} onChange={e => patch(oi, 'endName', e.target.value)} /></Field>}<Field label="End customer phone"><input value={d.endPhone} onChange={e => patch(oi, 'endPhone', e.target.value)} /></Field></div>}
      <div className="form-grid"><Field label="Order source"><Select value={d.source} onChange={v => patch(oi, 'source', v)}><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="phone">Phone</option><option value="social_media">Social Media</option><option value="walk_in">Walk-in</option><option value="online_marketplace">Online Marketplace</option></Select></Field><Field label="Advance amount noted"><input type="number" min="0" step="0.01" value={d.advance} onChange={e => patch(oi, 'advance', e.target.value)} /></Field></div><h3>Items on this order</h3>{d.lines.map((l: any, li: number) => <div className="purchase-line" key={li}><Field label="Item"><Select value={l.itemId} onChange={v => patchLine(oi, li, 'itemId', v)}><option value="">Select item</option>{items.filter(i => i.is_active !== false && i.can_be_sold !== false).map(i => <option key={txt(i.id)} value={txt(i.id)}>{txt(i.item_code)} — {txt(i.name)}</option>)}</Select></Field><Field label="Quantity"><input type="number" min="0" step="0.001" value={l.quantity} onChange={e => patchLine(oi, li, 'quantity', e.target.value)} /></Field><Field label="Selling rate"><input type="number" min="0" step="0.01" value={l.rate} onChange={e => patchLine(oi, li, 'rate', e.target.value)} /></Field></div>)}<button className="add-row-button" onClick={() => patch(oi, 'lines', [...d.lines, { itemId: '', quantity: '', rate: '' }])}>＋ Add item row</button><div className="form-grid"><Field label="Requests"><textarea value={d.requests} onChange={e => patch(oi, 'requests', e.target.value)} /></Field><Field label="Notes"><textarea value={d.notes} onChange={e => patch(oi, 'notes', e.target.value)} /></Field></div></div>)}<button className="add-row-button" onClick={() => setDrafts(x => [...x, blankOrder()])}>＋ Add another customer order</button><Status message={message} error={error} /><button className="primary-button" onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save received orders'}</button></Modal>}
    <div className="console-panel" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Orders awaiting planning / confirmation</h2></div>{orders.filter(o => ['received', 'production_planned'].includes(txt(o.status))).map(o => <div className="workflow-row" key={txt(o.id)}><div><strong>{txt(o.business_code)}</strong><span>{txt(o.billing_customer_name)} · {txt(o.status)} · {txt(o.ordered_quantity)}</span></div><button className="secondary-button" onClick={() => openPlan(o)}>{o.status === 'received' ? 'Prepare plan & reserve' : 'Confirm order'}</button></div>)}{!orders.some(o => ['received', 'production_planned'].includes(txt(o.status))) && <p className="table-message">No orders awaiting planning.</p>}</div>
    {selected && <Modal title={`Order ${txt(selected.business_code)} — Plan & Reserve`} close={() => setSelected(null)} wide><p className="page-intro">Finished stock is reserved first. Shortfall is planned against the selected recipe version and its ingredient stock is reserved.</p>{lines.map(l => <div className="purchase-line" key={txt(l.id)}><div className="field"><span>Item</span><div><strong>{txt(l.itemCode)}</strong> — {txt(l.itemName)}</div></div><Field label="Ordered"><input value={txt(l.ordered_quantity)} readOnly /></Field><Field label="Available"><input value={String(l.available)} readOnly /></Field><Field label="Production needed"><input value={String(l.shortfall)} readOnly /></Field>{Number(l.shortfall) > 0 && <Field label="Recipe version"><Select value={l.recipeVersionId} onChange={v => setLines(x => x.map(z => z.id === l.id ? { ...z, recipeVersionId: v } : z))}><option value="">Select recipe version</option>{l.recipeOptions.map((r: any) => <option key={txt(r.id)} value={txt(r.id)}>v{txt(r.version_number)} — {txt(r.recipes?.name)}</option>)}</Select></Field>}</div>)}<Status message={message} error={error} />{selected.status === 'received' ? <button className="primary-button" onClick={prepare}>Prepare plan & reserve inventory</button> : <button className="primary-button" onClick={confirm}>Confirm order</button>}</Modal>}
    <div className="console-panel" style={{ marginTop: 18 }}><div className="panel-heading"><h2>All orders</h2></div><DataTable table="v_orders_list" /></div></Page>
}
function blankOrder() { return { party: 'direct', customerId: '', subAgentId: '', endMode: 'existing', endCustomerId: '', endName: '', endPhone: '', source: 'whatsapp', date: today(), dispatchDate: '', advance: '', requests: '', notes: '', lines: [{ itemId: '', quantity: '', rate: '' }] } }

function Inventory() {
 const[items]=useRows('items'),[units]=useRows('units'); const[open,setOpen]=useState(false); const[kind,setKind]=useState<'out'|'adjust'>('out'); const[iid,setIid]=useState(''); const[uid,setUid]=useState(''); const[qty,setQty]=useState(''); const[reason,setReason]=useState('damage'); const[notes,setNotes]=useState(''); const[msg,setMsg]=useState(''); const[error,setError]=useState(false)
 const submit=async()=>{const n=Number(qty);if(!iid||!uid||!n){setError(true);setMsg('Item, unit and a non-zero quantity are required.');return}const rpc=kind==='out'?'record_stock_out':'record_stock_adjustment';const args=kind==='out'?{p_item_id:iid,p_quantity:n,p_unit_id:uid,p_stock_out_date:today(),p_reason:reason,p_notes:notes||null}:{p_item_id:iid,p_quantity_delta:n,p_unit_id:uid,p_adjustment_date:today(),p_reason:reason,p_notes:notes||null};const{error:e}=await sb().rpc(rpc,args);if(e){setError(true);setMsg(e.message);return}setOpen(false);setError(false);setMsg(kind==='out'?'Stock Out recorded using FIFO.':'Stock Adjustment recorded.');setQty('');setNotes('')}
 return <Page title="Inventory" description="Current stock comes from inventory transactions. Reservations are commitments; physical stock changes only through controlled movements."><button className="primary-button" onClick={()=>setOpen(true)}>+ Stock Action</button>{open&&<Modal title="Stock Action" close={()=>setOpen(false)}><div className="master-tabs"><button className={kind==='out'?'tab-active':''} onClick={()=>setKind('out')}>Stock Out</button><button className={kind==='adjust'?'tab-active':''} onClick={()=>setKind('adjust')}>Stock Adjustment</button></div><div className="form-grid"><Field label="Item"><Select value={iid} onChange={setIid}><option value="">Select item</option>{items.map(i=><option key={txt(i.id)} value={txt(i.id)}>{txt(i.item_code)} — {txt(i.name)}</option>)}</Select></Field><Field label="Unit"><Select value={uid} onChange={setUid}><option value="">Select unit</option>{units.map(u=><option key={txt(u.id)} value={txt(u.id)}>{txt(u.name)} ({txt(u.symbol)})</option>)}</Select></Field><Field label={kind==='out'?'Quantity':'Adjustment (+ adds / − removes)'}><input type="number" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Reason"><Select value={reason} onChange={setReason}><option value="damage">Damage</option><option value="expiry">Expiry</option><option value="sample">Sample</option><option value="wastage">Wastage</option><option value="personal_use">Personal use</option><option value="production">Production</option><option value="correction">Correction</option><option value="other">Other</option></Select></Field></div><Field label="Notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><Status message={msg} error={error}/><button className="primary-button" onClick={submit}>Record</button></Modal>}<div className="console-panel" style={{marginTop:18}}><div className="panel-heading"><h2>Current stock</h2></div><DataTable table="v_inventory_current"/></div><div className="console-panel" style={{marginTop:18}}><div className="panel-heading"><h2>Inventory movements</h2></div><DataTable table="inventory_transactions"/></div></Page>
}

function Production() {
 const[batches,reload]=useRows('v_production_batches_list'); const[open,setOpen]=useState(false); const[bid,setBid]=useState(''); const[selected,setSelected]=useState<Row|null>(null); const[plan,setPlan]=useState<any[]>([]); const[out,setOut]=useState(''); const[msg,setMsg]=useState(''); const[error,setError]=useState(false)
 const choose=async(id:string)=>{setBid(id);const b=batches.find(x=>txt(x.id)===id);setSelected(b??null);setOut(txt(b?.planned_output_quantity));if(!id){setPlan([]);return}const{data}=await sb().from('production_batch_plan_lines').select('id,ingredient_item_id,planned_quantity,unit_id').eq('production_batch_id',id).order('id');setPlan((data??[]).map(x=>({id:x.id,itemId:txt(x.ingredient_item_id),unitId:txt(x.unit_id),planned:Number(x.planned_quantity),actual:Number(x.planned_quantity)})))}
 const approve=async()=>{if(!bid)return;const{data:u}=await sb().auth.getUser();const{error:e}=await sb().from('production_batches').update({wife_approval_status:'approved',approved_by:u.user?.id??null,approved_at:new Date().toISOString()}).eq('id',bid);if(e){setError(true);setMsg(e.message);return}setError(false);setMsg('Production batch approved.');await reload()}
 const start=async()=>{const{error:e}=await sb().rpc('start_production_batch',{p_production_batch_id:bid});if(e){setError(true);setMsg(e.message);return}setError(false);setMsg('Production started. Reserved ingredients are now being used for this batch.');await reload()}
 const complete=async()=>{if(!selected)return;const cons=plan.filter(x=>x.actual>0).map(x=>({ingredient_item_id:x.itemId,actual_quantity:Number(x.actual),unit_id:x.unitId}));if(!cons.length||Number(out)<=0){setError(true);setMsg('Actual ingredient consumption and output are required.');return}const{error:e}=await sb().rpc('complete_production',{p_production_batch_id:bid,p_consumptions:cons,p_outputs:[{output_item_id:selected.output_item_id,quantity:Number(out),unit_id:selected.output_unit_id}]});if(e){setError(true);setMsg(e.message);return}setError(false);setMsg('Production completed. Ingredient stock was consumed FIFO and output stock was created.');await reload();setOpen(false)}
 return <Page title="Production" description="Order-linked production shows the recipe version, planned ingredients, actual consumption and batch output. Wife approval is required before production starts."><button className="primary-button" onClick={()=>setOpen(true)}>+ Review Production</button>{open&&<Modal title="Production batch" close={()=>setOpen(false)} wide><Field label="Production batch"><Select value={bid} onChange={choose}><option value="">Select batch</option>{batches.filter(b=>txt(b.status)!=='completed').map(b=><option key={txt(b.id)} value={txt(b.id)}>{txt(b.business_code)} — {txt(b.output_item_name)} — {txt(b.status)} / {txt(b.wife_approval_status)}</option>)}</Select></Field>{selected&&<><div className="form-grid"><Field label="Order"><input value={txt(selected.order_code)} readOnly /></Field><Field label="Recipe version"><input value={selected.recipe_version==null?'':`v${selected.recipe_version}`} readOnly /></Field><Field label="Planned output"><input value={txt(selected.planned_output_quantity)} readOnly /></Field><Field label="Actual output"><input type="number" min="0" step="0.001" value={out} onChange={e=>setOut(e.target.value)} /></Field></div><div className="console-panel"><div className="panel-heading"><h2>Ingredients</h2></div>{plan.map((p,i)=><div className="purchase-line" key={txt(p.id)}><Field label="Ingredient"><input value={txt(p.itemId)} readOnly /></Field><Field label="Planned"><input value={String(p.planned)} readOnly /></Field><Field label="Actual"><input type="number" min="0" step="0.001" value={p.actual} onChange={e=>setPlan(x=>x.map((z,n)=>n===i?{...z,actual:Number(e.target.value)}:z))}/></Field></div>)}</div><Status message={msg} error={error}/>{selected.wife_approval_status!=='approved'&&<button className="secondary-button" onClick={approve}>Approve production</button>}{selected.wife_approval_status==='approved'&&selected.status==='planned'&&<button className="secondary-button" onClick={start}>Start production</button>}{selected.status==='in_progress'&&<button className="primary-button" onClick={complete}>Complete production</button>}</>}</Modal>}<div className="console-panel"><div className="panel-heading"><h2>Production batches</h2></div><DataTable table="v_production_batches_list"/></div></Page>
}

function Sales() {
 const[orders]=useRows('orders'); const[dispatches,reload]=useRows('dispatches'); const[items]=useRows('items'); const[open,setOpen]=useState(false); const[oid,setOid]=useState(''); const[method,setMethod]=useState('own_delivery'); const[dispatchId,setDispatchId]=useState(''); const[lines,setLines]=useState<any[]>([]); const[msg,setMsg]=useState(''); const[error,setError]=useState(false)
 const chooseOrder=async(id:string)=>{setOid(id);setDispatchId('');if(!id){setLines([]);return}const{data}=await sb().from('order_lines').select('id,item_id,ordered_quantity,dispatched_quantity').eq('order_id',id);setLines((data??[]).map(x=>({...x,quantity:Math.max(0,Number(x.ordered_quantity)-Number(x.dispatched_quantity||0))})))}
 const dispatch=async()=>{const selected=lines.filter(x=>Number(x.quantity)>0).map(x=>({order_line_id:x.id,quantity:Number(x.quantity)}));if(!oid||!selected.length){setError(true);setMsg('Select an order and at least one dispatch quantity.');return}const{error:e}=await sb().rpc('dispatch_order',{p_order_id:oid,p_dispatch_date:today(),p_method:method,p_lines:selected});if(e){setError(true);setMsg(e.message);return}setError(false);setMsg('Dispatch completed. Select the actual dispatch before creating the Sale & Invoice.');await reload()}
 const invoice=async()=>{if(!dispatchId){setError(true);setMsg('Select the actual completed dispatch.');return}const{error:e}=await sb().rpc('create_sale_invoice',{p_dispatch_id:dispatchId});if(e){setError(true);setMsg(e.message);return}setError(false);setMsg('Sale and Invoice created from the selected dispatch.');await reload()}
 return <Page title="Sales & Invoices" description="Dispatch is the physical stock movement. Sale and Invoice are created from the actual completed dispatch, so stock is not reduced twice."><button className="primary-button" onClick={()=>setOpen(true)}>+ Dispatch / Sale / Invoice</button>{open&&<Modal title="Dispatch → Sale → Invoice" close={()=>setOpen(false)} wide><div className="form-grid"><Field label="Order"><Select value={oid} onChange={chooseOrder}><option value="">Select order</option>{orders.filter(o=>['confirmed','in_production','ready','partially_dispatched'].includes(txt(o.status))).map(o=><option key={txt(o.id)} value={txt(o.id)}>{txt(o.business_code)} — {txt(o.status)}</option>)}</Select></Field><Field label="Dispatch method"><Select value={method} onChange={setMethod}><option value="own_delivery">Own delivery</option><option value="customer_pickup">Customer pickup</option><option value="courier">Courier</option><option value="transport">Transport</option><option value="other">Other</option></Select></Field></div>{lines.map((l,i)=>{const it=items.find(x=>txt(x.id)===txt(l.item_id));return <div className="purchase-line" key={txt(l.id)}><div className="field"><span>Item</span><div>{txt(it?.item_code)} — {txt(it?.name)}</div></div><Field label="Remaining"><input value={String(Math.max(0,Number(l.ordered_quantity)-Number(l.dispatched_quantity||0)))} readOnly/></Field><Field label="Dispatch quantity"><input type="number" min="0" step="0.001" value={l.quantity} onChange={e=>setLines(v=>v.map((z,n)=>n===i?{...z,quantity:e.target.value}:z))}/></Field></div>})}<button className="primary-button" onClick={dispatch}>Dispatch selected quantities</button><Field label="Completed dispatch to invoice"><Select value={dispatchId} onChange={setDispatchId}><option value="">Select actual dispatch</option>{dispatches.filter(d=>txt(d.status)==='dispatched').map(d=><option key={txt(d.id)} value={txt(d.id)}>{txt(d.business_code)} — {txt(d.dispatch_date)}</option>)}</Select></Field><button className="primary-button" onClick={invoice}>Create Sale & Invoice</button><Status message={msg} error={error}/></Modal>}
 <div className="console-grid"><div className="console-panel"><div className="panel-heading"><h2>Dispatches</h2></div><DataTable table="dispatches"/></div><div className="console-panel"><div className="panel-heading"><h2>Sales</h2></div><DataTable table="sales"/></div><div className="console-panel"><div className="panel-heading"><h2>Invoices</h2></div><DataTable table="invoices"/></div></div></Page>
}

function Payments() {
 const[customers]=useRows('customers'); const[suppliers]=useRows('suppliers'); const[invoices]=useRows('invoices'); const[purchases]=useRows('purchases'); const[open,setOpen]=useState(false); const[direction,setDirection]=useState<'customer'|'supplier'>('customer'); const[party,setParty]=useState(''); const[amount,setAmount]=useState(''); const[method,setMethod]=useState('upi'); const[ref,setRef]=useState(''); const[notes,setNotes]=useState(''); const[allocs,setAllocs]=useState<any[]>([]); const[msg,setMsg]=useState(''); const[error,setError]=useState(false)
 const addAlloc=()=>setAllocs(x=>[...x,direction==='customer'?{id:'',amount:''}:{id:'',amount:''}]); const patchAlloc=(i:number,k:string,v:string)=>setAllocs(x=>x.map((a,n)=>n===i?{...a,[k]:v}:a));
 const submit=async()=>{if(!party||Number(amount)<=0){setError(true);setMsg('Select the party and enter a positive payment amount.');return}const clean=allocs.filter(a=>a.id&&Number(a.amount)>0).map(a=>direction==='customer'?{invoice_id:a.id,amount:Number(a.amount)}:{purchase_id:a.id,amount:Number(a.amount)});const allocated=clean.reduce((s,a)=>s+Number(a.amount),0);if(allocated>Number(amount)){setError(true);setMsg('Allocated amount cannot exceed the payment amount.');return}const rpc=direction==='customer'?'record_customer_payment_allocations':'record_supplier_payment_allocations';const args=direction==='customer'?{p_customer_id:party,p_amount:Number(amount),p_payment_date:today(),p_method:method,p_allocations:clean,p_upi_reference:ref||null,p_notes:notes||null}:{p_supplier_id:party,p_amount:Number(amount),p_payment_date:today(),p_method:method,p_allocations:clean,p_upi_reference:ref||null,p_notes:notes||null};const{error:e}=await sb().rpc(rpc,args);if(e){setError(true);setMsg(e.message);return}setError(false);setMsg(Number(amount)-allocated>0?`Payment recorded. ₹ ${(Number(amount)-allocated).toFixed(2)} kept as an advance.`:'Payment recorded and allocated.');setAmount('');setRef('');setNotes('');setAllocs([])}
 const partyInvoices=invoices.filter(i=>direction==='customer'&&(!party||txt(i.billing_customer_id)===party)&&Number(i.amount_due)>0); const partyPurchases=purchases.filter(p=>direction==='supplier'&&(!party||txt(p.supplier_id)===party));
 return <Page title="Payments" description="Record customer receipts or supplier payments. One payment may cover multiple documents; any unallocated balance is recorded as an advance."><button className="primary-button" onClick={()=>setOpen(true)}>+ Record Payment</button>{open&&<Modal title={direction==='customer'?'Receive Customer Payment':'Pay Supplier'} close={()=>setOpen(false)} wide><div className="master-tabs"><button className={direction==='customer'?'tab-active':''} onClick={()=>{setDirection('customer');setParty('');setAllocs([])}}>Customer Receipt</button><button className={direction==='supplier'?'tab-active':''} onClick={()=>{setDirection('supplier');setParty('');setAllocs([])}}>Supplier Payment</button></div><Field label={direction==='customer'?'Customer':'Supplier'}><Select value={party} onChange={setParty}><option value="">Select {direction}</option>{(direction==='customer'?customers:suppliers).map(x=><option key={txt(x.id)} value={txt(x.id)}>{txt(x.name||x.business_name)} — {txt(x.business_code)}</option>)}</Select></Field><div className="form-grid"><Field label="Amount"><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Method"><Select value={method} onChange={setMethod}><option value="upi">UPI</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></Select></Field><Field label="Payment reference"><input value={ref} onChange={e=>setRef(e.target.value)}/></Field><Field label="Notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div><h3>{direction==='customer'?'Allocate to invoices':'Allocate to purchases'}</h3>{allocs.map((a,i)=><div className="purchase-line" key={i}><Field label={direction==='customer'?'Invoice':'Purchase'}><Select value={a.id} onChange={v=>patchAlloc(i,'id',v)}><option value="">Select document</option>{(direction==='customer'?partyInvoices:partyPurchases).map(x=><option key={txt(x.id)} value={txt(x.id)}>{txt(x.business_code)} — ₹ {Number(direction==='customer'?x.amount_due:(x.total_amount||x.total||0)).toFixed(2)}</option>)}</Select></Field><Field label="Allocation"><input type="number" min="0" step="0.01" value={a.amount} onChange={e=>patchAlloc(i,'amount',e.target.value)}/></Field></div>)}<button className="add-row-button" onClick={addAlloc}>＋ Add allocation</button><Status message={msg} error={error}/><button className="primary-button" onClick={submit}>Record payment</button></Modal>}
 <div className="console-grid"><div className="console-panel"><div className="panel-heading"><h2>Customer receipts</h2></div><DataTable table="customer_payments"/></div><div className="console-panel"><div className="panel-heading"><h2>Supplier payments</h2></div><DataTable table="supplier_payments"/></div></div></Page>
}

export default function OperationsConsoleFinal2({ module }: { module: Module }) {
 if (module === 'orders') return <Orders />
 if (module === 'inventory') return <Inventory />
 if (module === 'production') return <Production />
 if (module === 'sales') return <Sales />
 return <Payments />
}
