'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Row = Record<string, any>
type Props = { module: 'purchases' | 'inventory' | 'production' | 'orders' | 'sales' | 'payments' }

function useRows(table: string) {
  const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const reload = async () => { setLoading(true); let query = createClient().from(table).select('*'); if (!table.startsWith('v_')) query = query.order('created_at', { ascending: false }); const { data, error } = await query.limit(100); setRows(data ?? []); setError(error?.message ?? ''); setLoading(false) }
  useEffect(() => { reload() }, [table]); return { rows, error, loading, reload }
}
function Page({ title, children }: { title: string; children: React.ReactNode }) { return <section className="page-panel"><div className="section-label">Mane Masala</div><h1>{title}</h1><p className="page-intro">Real operational workflow connected to the persistent database.</p>{children}</section> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="console-panel"><div className="panel-heading"><h2>{title}</h2></div>{children}</div> }
function Status({ message, error }: { message: string; error?: boolean }) { return message ? <p className={`form-status ${error ? 'form-status-error' : ''}`}>{message}</p> : null }
function Select({ value, onChange, children }: any) { return <select value={value} onChange={e => onChange(e.target.value)}>{children}</select> }
function Simple({ rows, fields }: { rows: Row[]; fields: string[] }) { return <div className="table-wrap"><table><thead><tr>{fields.map(f => <th key={f}>{f.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={r.id ?? i}>{fields.map(f => <td key={f}>{String(r[f] ?? '')}</td>)}</tr>)}</tbody></table></div> }

function Purchases() {
  const sb=createClient(), p=useRows('purchases'), suppliers=useRows('suppliers'), items=useRows('items'); const [supplierId,setSupplierId]=useState(''),[itemId,setItemId]=useState(''),[qty,setQty]=useState(''),[rate,setRate]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState('')
  const createPurchase=async()=>{const item=items.rows.find(x=>x.id===itemId);if(!supplierId||!item||!qty){setMessage('Supplier, item and quantity are required.');return}const {data,error}=await sb.from('purchases').insert({supplier_id:supplierId,purchase_date:new Date().toISOString().slice(0,10),entry_date:new Date().toISOString(),purchase_source:'Other',financial_status:'unpaid',workflow_status:'received'}).select().single();if(error){setMessage(error.message);return}const {error:e2}=await sb.from('purchase_lines').insert({purchase_id:data.id,item_id:itemId,billed_quantity:Number(qty),unit_id:item.base_unit_id,unit_rate:rate?Number(rate):null,line_total:rate?Number(qty)*Number(rate):null});setMessage(e2?.message??'Purchase created. Now receive and inspect it.');setSelected(data.id);await p.reload()}
  const receive=async()=>{if(!selected){setMessage('Select a purchase first.');return}const {data:lines,error:e}=await sb.from('purchase_lines').select('id,billed_quantity').eq('purchase_id',selected);if(e||!lines?.length){setMessage(e?.message??'No purchase line found.');return}const payload=lines.map(x=>({purchase_line_id:x.id,received_quantity:x.billed_quantity,accepted_quantity:x.billed_quantity,rejected_quantity:0,replacement_quantity:0}));const {data,error}=await sb.rpc('receive_purchase',{p_purchase_id:selected,p_lines:payload});setMessage(error?.message??`Received successfully: ${JSON.stringify(data)}`);await p.reload()}
  return <Page title="Purchases"><div className="console-grid"><Panel title="New purchase"><div className="form-grid"><Select value={supplierId} onChange={setSupplierId}><option value="">Supplier</option>{suppliers.rows.map(x=><option key={x.id} value={x.id}>{x.business_name}</option>)}</Select><Select value={itemId} onChange={setItemId}><option value="">Item</option>{items.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><input type="number" min="0" step="0.001" placeholder="Quantity" value={qty} onChange={e=>setQty(e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Rate" value={rate} onChange={e=>setRate(e.target.value)}/><button onClick={createPurchase}>Create purchase</button></div></Panel><Panel title="Receive & inspect"><div className="form-grid"><Select value={selected} onChange={setSelected}><option value="">Purchase</option>{p.rows.map(x=><option key={x.id} value={x.id}>{x.business_code||x.id.slice(0,8)} — {x.workflow_status}</option>)}</Select><button onClick={receive}>Accept received stock</button></div><Status message={message} error={message.includes('error')||message.includes('required')}/></Panel></div><Panel title="Purchase history"><Simple rows={p.rows} fields={['business_code','supplier_id','purchase_date','financial_status','workflow_status']}/></Panel></Page>
}
function Orders() {
  const sb=createClient(),o=useRows('orders'),customers=useRows('customers'),items=useRows('items');const [customerId,setCustomerId]=useState(''),[itemId,setItemId]=useState(''),[qty,setQty]=useState(''),[rate,setRate]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState('')
  const createOrder=async()=>{const item=items.rows.find(x=>x.id===itemId);if(!customerId||!item||!qty){setMessage('Customer, item and quantity are required.');return}const {data,error}=await sb.from('orders').insert({customer_id:customerId,order_date:new Date().toISOString().slice(0,10),source:'Other',status:'draft'}).select().single();if(error){setMessage(error.message);return}const {error:e2}=await sb.from('order_lines').insert({order_id:data.id,item_id:itemId,ordered_quantity:Number(qty),unit_id:item.base_unit_id,selling_rate:Number(rate||0)});setMessage(e2?.message??'Order created. Confirm it to reserve available stock.');setSelected(data.id);await o.reload()}
  const confirm=async()=>{if(!selected){setMessage('Select an order.');return}const {data,error}=await sb.rpc('confirm_order_reserve',{p_order_id:selected});setMessage(error?.message??`Order confirmed. ${JSON.stringify(data)}`);await o.reload()}
  return <Page title="Orders"><div className="console-grid"><Panel title="New order"><div className="form-grid"><Select value={customerId} onChange={setCustomerId}><option value="">Customer</option>{customers.rows.map(x=><option key={x.id} value={x.id}>{x.name||x.business_name||x.id.slice(0,8)}</option>)}</Select><Select value={itemId} onChange={setItemId}><option value="">Item</option>{items.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><input type="number" placeholder="Quantity" value={qty} onChange={e=>setQty(e.target.value)}/><input type="number" placeholder="Selling rate" value={rate} onChange={e=>setRate(e.target.value)}/><button onClick={createOrder}>Create order</button></div></Panel><Panel title="Confirm & reserve"><div className="form-grid"><Select value={selected} onChange={setSelected}><option value="">Order</option>{o.rows.map(x=><option key={x.id} value={x.id}>{x.business_code||x.id.slice(0,8)} — {x.status}</option>)}</Select><button onClick={confirm}>Confirm & reserve</button></div><Status message={message} error={message.includes('required')||message.includes('error')}/></Panel></div><Panel title="Order history"><Simple rows={o.rows} fields={['business_code','customer_id','order_date','status']}/></Panel></Page>
}
function DispatchSales(){const sb=createClient(),o=useRows('orders'),d=useRows('dispatches'),s=useRows('sales'),inv=useRows('invoices');const [orderId,setOrderId]=useState(''),[message,setMessage]=useState('');const dispatch=async()=>{if(!orderId){setMessage('Select an order.');return}const {data:lines,error:e}=await sb.from('order_lines').select('id,ordered_quantity,dispatched_quantity').eq('order_id',orderId);if(e||!lines?.length){setMessage(e?.message??'No order lines.');return}const payload=lines.map(x=>({order_line_id:x.id,quantity:Number(x.ordered_quantity)-Number(x.dispatched_quantity||0)})).filter(x=>x.quantity>0);const {data,error}=await sb.rpc('dispatch_order',{p_order_id:orderId,p_dispatch_date:new Date().toISOString().slice(0,10),p_method:'Other',p_lines:payload});setMessage(error?.message??`Dispatch completed: ${JSON.stringify(data)}`);await d.reload();await o.reload()};const invoice=async()=>{const x=d.rows[0];if(!x){setMessage('No dispatch yet.');return}const {data,error}=await sb.rpc('create_sale_invoice',{p_dispatch_id:x.id});setMessage(error?.message??`Sale and invoice created: ${JSON.stringify(data)}`);await s.reload();await inv.reload()};return <Page title="Dispatch → Sale → Invoice"><Panel title="Operational flow"><div className="form-grid"><Select value={orderId} onChange={setOrderId}><option value="">Confirmed order</option>{o.rows.filter(x=>['confirmed','production_planned','ready','partially_dispatched'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.business_code||x.id.slice(0,8)} — {x.status}</option>)}</Select><button onClick={dispatch}>Dispatch FIFO</button><button onClick={invoice}>Create sale & invoice</button></div><Status message={message} error={message.includes('error')||message.includes('Select')}/></Panel><div className="console-grid"><Panel title="Dispatches"><Simple rows={d.rows} fields={['id','order_id','dispatch_date','status']}/></Panel><Panel title="Invoices"><Simple rows={inv.rows} fields={['invoice_number','invoice_date','total_amount','amount_due','status']}/></Panel></div></Page>}
function Payments(){const sb=createClient(),inv=useRows('invoices'),pur=useRows('purchases'),customers=useRows('customers'),suppliers=useRows('suppliers');const [customerId,setCustomerId]=useState(''),[supplierId,setSupplierId]=useState(''),[invoiceId,setInvoiceId]=useState(''),[purchaseId,setPurchaseId]=useState(''),[amount,setAmount]=useState(''),[message,setMessage]=useState('');const payCustomer=async()=>{const {data,error}=await sb.rpc('record_customer_payment',{p_customer_id:customerId,p_amount:Number(amount),p_payment_date:new Date().toISOString().slice(0,10),p_method:'UPI',p_invoice_id:invoiceId||null});setMessage(error?.message??JSON.stringify(data));await inv.reload()};const paySupplier=async()=>{const {data,error}=await sb.rpc('record_supplier_payment',{p_supplier_id:supplierId,p_amount:Number(amount),p_payment_date:new Date().toISOString().slice(0,10),p_method:'UPI',p_purchase_id:purchaseId||null});setMessage(error?.message??JSON.stringify(data));await pur.reload()};return <Page title="Payments"><div className="console-grid"><Panel title="Receive from customer"><div className="form-grid"><Select value={customerId} onChange={setCustomerId}><option value="">Customer</option>{customers.rows.map(x=><option key={x.id} value={x.id}>{x.name||x.business_name}</option>)}</Select><Select value={invoiceId} onChange={setInvoiceId}><option value="">Invoice (optional)</option>{inv.rows.map(x=><option key={x.id} value={x.id}>{x.invoice_number||x.id.slice(0,8)} — {x.amount_due}</option>)}</Select><input type="number" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={payCustomer}>Record customer payment</button></div></Panel><Panel title="Pay supplier"><div className="form-grid"><Select value={supplierId} onChange={setSupplierId}><option value="">Supplier</option>{suppliers.rows.map(x=><option key={x.id} value={x.id}>{x.business_name}</option>)}</Select><Select value={purchaseId} onChange={setPurchaseId}><option value="">Purchase (optional)</option>{pur.rows.map(x=><option key={x.id} value={x.id}>{x.business_code||x.id.slice(0,8)}</option>)}</Select><input type="number" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={paySupplier}>Record supplier payment</button></div></Panel></div><Status message={message} error={message.includes('error')}/></Page>}
function Inventory(){const x=useRows('v_inventory_current');return <Page title="Inventory & FIFO"><Panel title="Current stock / reserved / available"><Simple rows={x.rows} fields={['name','current_stock','reserved_stock','available_stock','minimum_stock']}/></Panel></Page>}
function Production(){const sb=createClient(),p=useRows('production_batches'),items=useRows('items');const [batchId,setBatchId]=useState(''),[ingredientId,setIngredientId]=useState(''),[ingredientQty,setIngredientQty]=useState(''),[outputId,setOutputId]=useState(''),[outputQty,setOutputQty]=useState(''),[message,setMessage]=useState('');const approve=async()=>{const {error}=await sb.from('production_batches').update({wife_approval_status:'approved',approved_at:new Date().toISOString()}).eq('id',batchId);setMessage(error?.message??'Production approved.');await p.reload()};const complete=async()=>{const iu=items.rows.find(x=>x.id===ingredientId)?.base_unit_id,ou=items.rows.find(x=>x.id===outputId)?.base_unit_id;const {data,error}=await sb.rpc('complete_production',{p_production_batch_id:batchId,p_consumptions:[{ingredient_item_id:ingredientId,actual_quantity:Number(ingredientQty),unit_id:iu}],p_outputs:[{output_item_id:outputId,quantity:Number(outputQty),unit_id:ou}]});setMessage(error?.message??JSON.stringify(data));await p.reload()};return <Page title="Recipes & Production"><Panel title="Production approval and completion"><div className="form-grid"><Select value={batchId} onChange={setBatchId}><option value="">Production batch</option>{p.rows.filter(x=>x.status!=='completed').map(x=><option key={x.id} value={x.id}>{x.business_code||x.id.slice(0,8)} — {x.wife_approval_status}</option>)}</Select><Select value={ingredientId} onChange={setIngredientId}><option value="">Ingredient consumed</option>{items.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><input type="number" placeholder="Consumed quantity" value={ingredientQty} onChange={e=>setIngredientQty(e.target.value)}/><Select value={outputId} onChange={setOutputId}><option value="">Output item</option>{items.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><input type="number" placeholder="Actual output quantity" value={outputQty} onChange={e=>setOutputQty(e.target.value)}/><button onClick={approve}>Wife approval</button><button onClick={complete}>Complete production</button></div><Status message={message} error={message.includes('error')}/></Panel><Panel title="Production batches"><Simple rows={p.rows} fields={['business_code','output_item_id','planned_output_quantity','actual_output_quantity','status','wife_approval_status']}/></Panel></Page>}
export default function OperationsConsole({module}:Props){if(module==='purchases')return <Purchases/>;if(module==='orders')return <Orders/>;if(module==='sales')return <DispatchSales/>;if(module==='payments')return <Payments/>;if(module==='inventory')return <Inventory/>;return <Production/>}
