'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'

type R=Record<string,any>
const db=()=>createClient()
const s=(v:any)=>String(v??'')
const n=(v:any)=>Number(v??0)

function fmt(v:number,unit:string){return `${Number(v||0).toFixed(3).replace(/\.000$/,'')} ${unit}`}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Status({message,error}:{message:string,error:boolean}){return message?<p className={`form-status${error?' form-status-error':''}`} role="alert">{message}</p>:null}

export default function OrdersPartialReview(){
 const[orders,setOrders]=useState<R[]>([]),[items,setItems]=useState<R[]>([]),[units,setUnits]=useState<R[]>([]),[recipes,setRecipes]=useState<R[]>([]),[versions,setVersions]=useState<R[]>([])
 const[selectedId,setSelectedId]=useState(''),[selected,setSelected]=useState<R|null>(null),[lines,setLines]=useState<R[]>([]),[batches,setBatches]=useState<R[]>([]),[plans,setPlans]=useState<Record<string,R[]>>({}),[procurement,setProcurement]=useState<R[]>([]),[inventory,setInventory]=useState<Record<string,R>>({})
 const[extra,setExtra]=useState<Record<string,R>>({}),[partialQty,setPartialQty]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(false)

 const loadMasters=async()=>{const sb=db();const[c,i,u,r,v,o]=await Promise.all([sb.from('customers').select('id,name,business_code').eq('is_active',true),sb.from('items').select('*').eq('is_active',true),sb.from('units').select('*').eq('is_active',true),sb.from('recipes').select('id,name,output_item_id,status').eq('status','active'),sb.from('recipe_versions').select('*').eq('status','active').order('version_number'),sb.from('v_orders_list').select('*').in('status',['received','production_planned','confirmed','in_production']).order('order_date',{ascending:false})]);setItems(i.data??[]);setUnits(u.data??[]);setRecipes(r.data??[]);setVersions(v.data??[]);setOrders(o.data??[]);if(!selectedId&&o.data?.length)setSelectedId(s(o.data.find((x:any)=>s(x.business_code)==='ORD-TEST-PARTIAL-001')?.id||o.data[0]?.id))}
 useEffect(()=>{void loadMasters()},[])
 const unit=(id:string)=>s(units.find(u=>s(u.id)===id)?.symbol||units.find(u=>s(u.id)===id)?.name||id)
 const item=(id:string)=>items.find(i=>s(i.id)===id)
 const recipeName=(id:string)=>{const v=versions.find(x=>s(x.id)===id);const r=recipes.find(x=>s(x.id)===s(v?.recipe_id));return v&&r?`${s(r.name)} — v${s(v.version_number)}`:''}

 const open=async(id:string)=>{if(!id)return;setSelectedId(id);setMsg('');setErr(false);const sb=db();const order=orders.find(o=>s(o.id)===id);setSelected(order||null);const[{data:l,error:le},{data:b,error:be},{data:p,error:pe},{data:q,error:qe},{data:inv,error:ie}]=await Promise.all([sb.from('order_lines').select('*').eq('order_id',id).order('created_at'),sb.from('production_batches').select('*').eq('order_id',id).order('production_date'),sb.from('production_batch_plan_lines').select('*').eq('production_batch_id',id).order('created_at'),sb.from('order_line_procurement_requirements').select('*').eq('order_id',id).order('created_at'),sb.from('v_inventory_current').select('*')]);if(le||be||pe||qe||ie){setErr(true);setMsg(le?.message||be?.message||pe?.message||qe?.message||ie?.message||'Unable to load order');return}const im:Record<string,R>={};for(const x of inv??[])im[s(x.item_id)]=x;setInventory(im);setLines((l??[]).map(x=>({...x,item:item(s(x.item_id))})));setBatches(b??[]);const pm:Record<string,R[]>={};for(const x of p??[])pm[s(x.production_batch_id)]=[...(pm[s(x.production_batch_id)]??[]),x];setPlans(pm);setProcurement(q??[]);const next:Record<string,string>={};for(const x of b??[]){const pls=(pm[s(x.id)]??[]);const ratios=pls.map(pl=>{const available=n(im[s(pl.ingredient_item_id)]?.available_stock);return n(pl.planned_quantity)>0?available/n(pl.planned_quantity):Infinity});const suggested=Math.min(n(x.planned_output_quantity),...ratios.map((r:number)=>n(x.planned_output_quantity)*r));next[s(x.id)]=String(Math.max(0,Math.min(n(x.planned_output_quantity),suggested)).toFixed(3))}setPartialQty(next)}
 useEffect(()=>{if(selectedId)void open(selectedId)},[selectedId])

 const prepare=async()=>{setBusy('prepare');const selections=lines.filter(l=>n(l.ordered_quantity)>n(l.reserved_quantity)+n(l.produced_quantity)).map(l=>({order_line_id:l.id,recipe_version_id:versions.find(v=>recipes.some(r=>s(r.id)===s(v.recipe_id)&&s(r.output_item_id)===s(l.item_id)))?.id||''}));if(selections.some(x=>!x.recipe_version_id)){setBusy('');setErr(true);setMsg('Every line requiring production must have an active recipe version.');return}const{error}=await db().rpc('prepare_order_plan',{p_order_id:selectedId,p_recipe_selections:selections});setBusy('');if(error){setErr(true);setMsg(error.message);return}setErr(false);setMsg('Production plan prepared independently for each order line.');await open(selectedId)}
 const partial=async(b:R)=>{const qty=n(partialQty[s(b.id)]);if(!qty){setErr(true);setMsg('Enter the quantity to approve for this item.');return}setBusy(s(b.id));const{error}=await db().rpc('partial_approve_production_batch',{p_production_batch_id:b.id,p_approved_output:qty});setBusy('');if(error){setErr(true);setMsg(error.message);return}setErr(false);setMsg(`${s(b.business_code)} partially approved for ${qty} ${unit(s(b.output_unit_id))}.`);await open(selectedId)}
 const approve=async(b:R)=>{setBusy(`a-${b.id}`);const{error}=await db().rpc('approve_production_batch',{p_production_batch_id:b.id});setBusy('');if(error){setErr(true);setMsg(error.message);return}setErr(false);setMsg(`${s(b.business_code)} approved. This item can proceed independently.`);await open(selectedId)}
 const markPurchase=async(b:R)=>{setBusy(`p-${b.id}`);const{error}=await db().rpc('mark_production_pending_procurement',{p_production_batch_id:b.id});setBusy('');if(error){setErr(true);setMsg(error.message);return}setErr(false);setMsg('Purchase requirement recorded. This item remains pending until inward is completed.');await open(selectedId)}
 const revise=async(b:R)=>{const x=extra[s(b.id)]||{};const additional=x.item&&n(x.qty)>0?[{ingredient_item_id:x.item,quantity:n(x.qty),unit_id:item(x.item)?.base_unit_id}]:[];if(additional.length&&!additional[0].unit_id){setErr(true);setMsg('Selected raw material has no base unit.');return}setBusy(`r-${b.id}`);const{error}=await db().rpc('revise_production_plan',{p_production_batch_id:b.id,p_recipe_version_id:s(b.recipe_version_id),p_additional_ingredients:additional,p_permanent_recipe_change:x.mode==='permanent'});setBusy('');if(error){setErr(true);setMsg(error.message);return}setErr(false);setMsg('Recipe / additional raw material change saved to this production plan.');await open(selectedId)}

 const openProc=procurement.filter(q=>s(q.status)==='open')
 return <section className="page-panel">
  <div className="section-label">Mane Masala · Phase 4</div>
  <div className="master-header"><div><h1>Order Approval — Partial Review</h1><p className="page-intro">Each order line is reviewed independently. Recipe, additional raw material, approval and procurement remain inside the same item workflow.</p></div></div>
  <div className="console-panel"><div className="panel-heading"><div><h2>Browser review transaction</h2><span>TEST ONLY — do not dispatch or complete production during this review.</span></div><span className="status-pill">{s(selected?.status)}</span></div><Field label="Select order"><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select order...</option>{orders.map(o=><option key={s(o.id)} value={s(o.id)}>{s(o.business_code)} — {s(o.billing_customer_name)}</option>)}</select></Field></div>
  {selected&&<>
   <div className="console-panel"><div className="panel-heading"><div><h2>{s(selected.business_code)}</h2><span>{s(selected.billing_customer_name)} · {s(selected.order_date)}</span></div><span>{lines.length} order lines</span></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Ordered</th><th>Finished stock</th><th>Pending to produce</th><th>Approval state</th></tr></thead><tbody>{lines.map(l=><tr key={s(l.id)}><td><strong>{s(l.item?.business_code)}</strong><br/>{s(l.item?.name)}</td><td className="num">{fmt(n(l.ordered_quantity),unit(s(l.unit_id)))}</td><td className="num">{fmt(n(inventory[s(l.item_id)]?.available_stock),unit(s(l.unit_id)))}</td><td className="num">{fmt(n(l.production_pending_quantity||Math.max(0,n(l.ordered_quantity)-n(l.reserved_quantity)-n(l.produced_quantity))),unit(s(l.unit_id)))}</td><td><span className="status-pill">{s(l.production_approval_status||'pending')}</span>{l.production_block_reason&&<div className="muted">{s(l.production_block_reason)}</div>}</td></tr>)}</tbody></table></div>{!batches.length&&<div className="workflow-actions"><button className="primary-button" disabled={busy==='prepare'} onClick={prepare}>{busy==='prepare'?'Preparing…':'Prepare / recalculate production plan'}</button></div>}</div>
   {batches.map(b=>{const id=s(b.id),pls=plans[id]??[],qs=procurement.filter(q=>s(q.production_batch_id)===id&&s(q.status)==='open'),ex=extra[id]||{item:'',qty:'',mode:'one_time'},pending=s(b.wife_approval_status)!=='approved',line=lines.find(l=>s(l.id)===s(b.order_line_id));const remaining=Math.max(0,n(line?.ordered_quantity)-n(line?.reserved_quantity)-n(line?.produced_quantity)-n(line?.production_approved_quantity));return <div className="console-panel" key={id}>
    <div className="panel-heading"><div><h2>{s(line?.item?.business_code)} — {s(line?.item?.name)}</h2><span>{s(b.business_code)} · {pending?'Wife approval pending':'Approved'}</span></div><span className="status-pill">{s(b.wife_approval_status)}</span></div>
    <div className="plan-summary"><div><small>Recipe with version</small><strong>{recipeName(s(b.recipe_version_id))}</strong></div><div><small>Production target</small><strong>{fmt(n(b.planned_output_quantity),unit(s(b.output_unit_id)))}</strong></div><div><small>Remaining to produce</small><strong>{fmt(remaining,unit(s(b.output_unit_id)))}</strong></div></div>
    <div className="panel-heading"><h3>Raw material plan</h3><span>Needed quantity · available stock · reservation</span></div><div className="table-wrap"><table><thead><tr><th>SL NO</th><th>Raw Material</th><th>Needed Qty</th><th>Available Stock</th><th>Reserved</th><th>State</th></tr></thead><tbody>{pls.map((p,i)=>{const av=n(inventory[s(p.ingredient_item_id)]?.available_stock);const res=n(qs.find(q=>s(q.ingredient_item_id)===s(p.ingredient_item_id))?.available_quantity||0);const short=Math.max(0,n(p.planned_quantity)-res);return <tr key={s(p.id)}><td>{i+1}</td><td>{s(item(s(p.ingredient_item_id))?.business_code)} — {s(item(s(p.ingredient_item_id))?.name)}</td><td className="num">{fmt(n(p.planned_quantity),unit(s(p.unit_id)))}</td><td className="num">{fmt(av,unit(s(p.unit_id)))}</td><td className="num">{fmt(res,unit(s(p.unit_id)))}</td><td>{short>0?<span className="status-pill">Purchase required</span>:<span className="muted">Available</span>}</td></tr>})}</tbody></table></div>
    <div className="section-divider"/><div className="panel-heading"><div><h3>Recipe / additional raw material</h3><span>Standard review flow for every order line.</span></div></div><div className="form-grid"><Field label="Additional raw material"><select value={s(ex.item)} onChange={e=>setExtra(z=>({...z,[id]:{...ex,item:e.target.value}}))}><option value="">No additional material</option>{items.filter(i=>i.is_raw_material!==false&&s(i.id)!==s(line?.item_id)).map(i=><option key={s(i.id)} value={s(i.id)}>{s(i.business_code)} — {s(i.name)}</option>)}</select></Field><Field label="Additional quantity"><input type="number" min="0" step="0.001" value={s(ex.qty)} placeholder="0.000 — quantity in selected material unit" onChange={e=>setExtra(z=>({...z,[id]:{...ex,qty:e.target.value}}))}/></Field><Field label="Change type"><select value={s(ex.mode||'one_time')} onChange={e=>setExtra(z=>({...z,[id]:{...ex,mode:e.target.value}}))}><option value="one_time">This production only</option><option value="permanent">Save as new recipe version</option></select></Field></div><div className="workflow-actions"><button className="secondary-button" disabled={busy===`r-${id}`} onClick={()=>revise(b)}>{busy===`r-${id}`?'Saving…':'Update plan'}</button></div>
    {qs.length>0&&<div className="alert-panel"><strong>Urgent Procurement</strong><p>This item cannot start until the missing raw material is purchased and inwarded.</p>{qs.map(q=><div className="workflow-row" key={s(q.id)}><div><strong>{s(item(s(q.ingredient_item_id))?.business_code)} — {s(item(s(q.ingredient_item_id))?.name)}</strong><span>Immediately needed: {fmt(n(q.shortfall_quantity),unit(s(q.unit_id)))}</span></div><span className="status-pill">{s(q.priority)}</span></div>)}</div>}
    {pending&&<div className="workflow-actions"><button className="primary-button" disabled={!!qs.length||busy===id} onClick={()=>approve(b)}>{busy===id?'Approving…':'Approve this item'}</button>{!qs.length&&<><input className="compact-number" type="number" min="0" step="0.001" value={s(partialQty[id]||'')} placeholder="Partial qty" onChange={e=>setPartialQty(z=>({...z,[id]:e.target.value}))}/><button className="secondary-button" disabled={busy===id||!!qs.length} onClick={()=>partial(b)}>Approve Partially</button></>}{qs.length>0&&<button className="secondary-button" disabled={busy===`p-${id}`} onClick={()=>markPurchase(b)}>{busy===`p-${id}`?'Saving…':'Mark Purchase Required'}</button>}</div>}
   </div>})}
   <Status message={msg} error={err}/>
  </>}
 </section>
}
