'use client'

import { useEffect, useMemo, useState, type ReactNode } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import PurchaseAttachmentPanel from '@/components/purchase-attachment-panel'

type Row = Record<string, any>
const db=()=>createClient()
const today=()=>new Date().toISOString().slice(0,10)
const n=(v:any)=>Number(v||0)
const txt=(v:any)=>String(v??'')
const money=(v:any)=>`₹ ${n(v).toFixed(2)}`
function Field({label,children,help}:{label:string;children:ReactNode;help?:string}){return <label className="field"><span>{label}</span>{children}{help&&<small className="muted">{help}</small>}</label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop"><div className="modal-card purchase-modal"><div className="modal-header"><div><h3>{title}</h3></div><button className="secondary-button" type="button" onClick={close}>Cancel</button></div>{children}</div></div>}
const blank=()=>({itemId:'',qty:'',rate:'',discount:'0',gstRate:'',tax:'0',notes:''})

export default function PurchaseConsoleV3(){
 const [suppliers,setSuppliers]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[units,setUnits]=useState<Row[]>([])
 const [open,setOpen]=useState(false),[step,setStep]=useState<'entry'|'receipt'|'settlement'|'done'>('entry')
 const [supplierId,setSupplierId]=useState(''),[date,setDate]=useState(today()),[slip,setSlip]=useState(''),[source,setSource]=useState('other'),[notes,setNotes]=useState('')
 const [lines,setLines]=useState<Row[]>([blank()]),[discount,setDiscount]=useState('0'),[tax,setTax]=useState('0'),[delivery,setDelivery]=useState('0'),[transport,setTransport]=useState('0'),[loading,setLoading]=useState('0'),[unloading,setUnloading]=useState('0'),[packing,setPacking]=useState('0'),[other,setOther]=useState('0')
 const [purchase,setPurchase]=useState<Row|null>(null),[receiptLines,setReceiptLines]=useState<Row[]>([]),[settlement,setSettlement]=useState<Row[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(false),[saving,setSaving]=useState(false)
 const [supplierSearch,setSupplierSearch]=useState('')
 const load=async()=>{const [s,i,u]=await Promise.all([db().from('suppliers').select('id,business_code,business_name').eq('is_active',true).order('business_name'),db().from('items').select('id,item_code,business_code,name,item_type,purchase_unit_id,base_unit_id').eq('is_active',true).order('name'),db().from('units').select('id,name,symbol').eq('is_active',true).order('name')]);setSuppliers(s.data??[]);setItems(i.data??[]);setUnits(u.data??[])}
 useEffect(()=>{void load()},[])
 const update=(i:number,p:Row)=>setLines(v=>v.map((x,k)=>k===i?{...x,...p}:x))
 const gross=(l:Row)=>n(l.qty)*n(l.rate)
 const lineDisc=(l:Row)=>n(l.discount)
 const lineTax=(l:Row)=>{const rate=n(l.gstRate);const taxable=Math.max(0,gross(l)-lineDisc(l));return rate>0?Math.round(taxable*rate)/100:0}
 const lineTotal=(l:Row)=>Math.max(0,gross(l)-lineDisc(l)+lineTax(l))
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+lineTotal(l),0),[lines])
 const billTotal=Math.max(0,subtotal-n(discount)+n(tax)+n(delivery)+n(transport)+n(loading)+n(unloading)+n(packing)+n(other))
 const filteredSuppliers=suppliers.filter(s=>`${txt(s.business_code)} ${txt(s.business_name)}`.toLowerCase().includes(supplierSearch.toLowerCase()))
 const save=async()=>{setMessage('');setError(false);const valid=lines.filter(l=>l.itemId&&n(l.qty)>0);if(!supplierId){setError(true);setMessage('Please select the supplier.');return}if(!valid.length){setError(true);setMessage('Add at least one purchased item.');return}setSaving(true);const {data,error:e}=await db().rpc('create_purchase_entry',{p_supplier_id:supplierId,p_purchase_date:date,p_supplier_invoice_number:slip.trim()||null,p_purchase_source:source,p_lines:valid.map(l=>({item_id:l.itemId,billed_quantity:n(l.qty),unit_rate:l.rate===''?null:n(l.rate),discount_amount:lineDisc(l),tax_rate:n(l.gstRate),tax_amount:0,notes:txt(l.notes).trim()||null})),p_discount_amount:n(discount),p_delivery_charge:n(delivery),p_transport_charge:n(transport),p_loading_charge:n(loading),p_unloading_charge:n(unloading),p_packing_charge:n(packing),p_other_charge:n(other),p_tax_amount:n(tax),p_notes:notes.trim()||null});setSaving(false);if(e||!data){setError(true);setMessage(e?.message||'Could not save purchase.');return}const pid=txt(data.purchase_id);setPurchase({...data,id:pid});const {data:pl,error:pe}=await db().from('purchase_lines').select('id,item_id,billed_quantity,unit_id,unit_rate,line_total').eq('purchase_id',pid).order('created_at');if(pe){setError(true);setMessage(pe.message);return}setReceiptLines((pl??[]).map(x=>({...x,received_quantity:txt(x.billed_quantity),accepted_quantity:txt(x.billed_quantity),rejected_quantity:'0',inspection_notes:''})));setSettlement([]);setStep('receipt');setMessage(`Purchase ${txt(data.business_code)||pid} saved. Stock is NOT updated until you record receipt below.`)}  
 const receive=async()=>{if(!purchase){setError(true);setMessage('Purchase is not loaded. Please reopen it.');return}for(const l of receiptLines){const r=n(l.received_quantity),a=n(l.accepted_quantity),rej=n(l.rejected_quantity);if(r<0||r>n(l.billed_quantity)||a<0||rej<0||a+rej!==r){setError(true);setMessage('For each item, Received cannot exceed Billed and Accepted + Rejected must equal Received.');return}}setSaving(true);const {error:e}=await db().rpc('receive_purchase',{p_purchase_id:purchase.id,p_lines:receiptLines.map(l=>({purchase_line_id:l.id,received_quantity:n(l.received_quantity),accepted_quantity:n(l.accepted_quantity),rejected_quantity:n(l.rejected_quantity),replacement_quantity:0,received_batch_date:date,notes:txt(l.inspection_notes)||null})),p_received_at:new Date().toISOString()});setSaving(false);if(e){setError(true);setMessage(e.message);return}const next=receiptLines.map(l=>{const billed=n(l.billed_quantity),received=n(l.received_quantity),rejected=n(l.rejected_quantity),affected=Math.max(0,billed-received)+rejected;const value=billed>0?n(l.line_total)*affected/billed:0;return {...l,shortage:Math.max(0,billed-received),affected,adjustment:value,supplierResponse:affected?'pending':'not_required',settlement:affected?'credit':'',supplierNotes:''}});setSettlement(next);setStep('settlement');setError(false);setMessage('Receipt recorded. Accepted quantities are in inventory and applied to open Material Indent shortfalls where possible.')}
 const finalize=async()=>{if(!purchase){setError(true);setMessage('Purchase is not loaded.');return}setSaving(true);const {data,error:e}=await db().rpc('finalize_purchase_review',{p_purchase_id:purchase.id,p_lines:settlement.map(l=>({receipt_line_id:l.id,supplier_response:l.supplierResponse,supplier_settlement:l.supplierResponse==='accepted'?l.settlement:null,supplier_response_notes:l.supplierNotes||null}))});setSaving(false);if(e){setError(true);setMessage(e.message);return}setStep('done');setError(false);setMessage(`Purchase review saved.`)}  
 const reset=()=>{setOpen(false);setStep('entry');setSupplierId('');setSupplierSearch('');setSlip('');setNotes('');setLines([blank()]);setPurchase(null);setReceiptLines([]);setSettlement([]);setDiscount('0');setTax('0');setDelivery('0');setTransport('0');setLoading('0');setUnloading('0');setPacking('0');setOther('0');setMessage('');setError(false)}
 return <section className="page-panel">
  <div className="master-header"><div><div className="section-label">Mane Masala</div><h1>Purchases</h1><p className="page-intro">Stock updates only after receipt is recorded (accepted quantities).</p></div><button className="primary-button" type="button" onClick={()=>setOpen(true)}>New purchase</button></div>
  <div className="console-panel"><div className="panel-heading"><h2>Purchase process</h2><span>Purchase → Receive (posts stock) → Review → Complete</span></div><Link className="secondary-button" href="/transactions?table=v_purchases_list">View purchase history</Link></div>
  {open&&<Modal title={step==='entry'?'New purchase':step==='receipt'?'Receive & inspect (posts stock)':step==='settlement'?'Review shortages':'Purchase complete'} close={reset}>
   {step==='entry'&&<>
    <div className="form-grid"><Field label="Supplier"><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Select supplier</option>{filteredSuppliers.map(s=><option key={txt(s.id)} value={txt(s.id)}>{txt(s.business_name)}</option>)}</select></Field><Field label="Find supplier"><input value={supplierSearch} onChange={e=>setSupplierSearch(e.target.value)}/></Field><Field label="Purchase date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Supplier slip"><input value={slip} onChange={e=>setSlip(e.target.value)}/></Field><Field label="Source"><select value={source} onChange={e=>setSource(e.target.value)}><option value="other">Other</option><option value="walk_in">Walk-in</option><option value="phone">Phone</option><option value="whatsapp">WhatsApp</option><option value="delivery">Delivery</option></select></Field></div>
    <div className="console-panel"><div className="panel-heading"><h3>Items</h3></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Discount</th><th>GST %</th><th></th></tr></thead><tbody>{lines.map((l,i)=>{const it=items.find(x=>txt(x.id)===txt(l.itemId))||{};return <tr key={i}><td><select value={l.itemId} onChange={e=>{const item=items.find(x=>txt(x.id)===e.target.value);update(i,{itemId:e.target.value,unitId:item?.purchase_unit_id||item?.base_unit_id||''})}}><option value="">Select item</option>{items.map(it=><option key={txt(it.id)} value={txt(it.id)}>{txt(it.item_code||it.business_code)} — {txt(it.name)}</option>)}</select></td><td><input type="number" min="0" step="0.001" value={l.qty} onChange={e=>update(i,{qty:e.target.value})}/></td><td><input type="number" min="0" step="0.01" value={l.rate} onChange={e=>update(i,{rate:e.target.value})}/></td><td><input type="number" min="0" step="0.01" value={l.discount} onChange={e=>update(i,{discount:e.target.value})}/></td><td><input type="number" min="0" step="0.01" value={l.gstRate} onChange={e=>update(i,{gstRate:e.target.value})}/></td><td><button type="button" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter((_,k)=>k!==i))}>Remove</button></td></tr>})}</tbody></table></div><button className="secondary-button" type="button" onClick={()=>setLines(v=>[...v,blank()])}>+ Add item</button></div>
    <div className="purchase-total"><strong>Total</strong><strong>{money(billTotal)}</strong></div><div className="purchase-actions"><button className="secondary-button" type="button" onClick={reset}>Cancel</button><button className="primary-button" type="button" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save & receive goods'}</button></div>
   </>}
   {step==='receipt'&&<><p className="page-intro"><strong>This step posts stock.</strong> Accepted qty updates inventory and Material Indent shortfalls.</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Billed</th><th>Received</th><th>Accepted</th><th>Rejected</th></tr></thead><tbody>{receiptLines.map((l,i)=>{const it=items.find(x=>txt(x.id)===txt(l.item_id))||{};return <tr key={txt(l.id)}><td>{txt(it.name)}</td><td>{txt(l.billed_quantity)}</td><td><input type="number" min="0" step="0.001" value={l.received_quantity} onChange={e=>setReceiptLines(v=>v.map((x,k)=>k===i?{...x,received_quantity:e.target.value,accepted_quantity:e.target.value,rejected_quantity:'0'}:x))}/></td><td><input type="number" min="0" step="0.001" value={l.accepted_quantity} onChange={e=>setReceiptLines(v=>v.map((x,k)=>k===i?{...x,accepted_quantity:e.target.value,rejected_quantity:String(Math.max(0,n(x.received_quantity)-n(e.target.value)))}:x))}/></td><td><input type="number" min="0" step="0.001" value={l.rejected_quantity} onChange={e=>setReceiptLines(v=>v.map((x,k)=>k===i?{...x,rejected_quantity:e.target.value,accepted_quantity:String(Math.max(0,n(x.received_quantity)-n(e.target.value)))}:x))}/></td></tr>})}</tbody></table></div><div className="purchase-actions"><button className="primary-button" type="button" disabled={saving} onClick={()=>void receive()}>{saving?'Saving…':'Save receipt (post stock)'}</button></div></>}
   {step==='settlement'&&<><p className="page-intro">Review shortages / damage and supplier response.</p><div className="purchase-actions"><button className="primary-button" type="button" disabled={saving} onClick={()=>void finalize()}>{saving?'Saving…':'Complete purchase'}</button></div></>}
   {step==='done'&&<><p className="page-intro">Stock posted. Material Indent updated where shortfalls matched.</p><button className="secondary-button" type="button" onClick={reset}>Close</button></>}
  </Modal>}
  {message&&<p className={`form-status${error?' form-status-error':''}`} role="alert">{message}</p>}
 </section>
}
