'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Row = Record<string, any>
const db=()=>createClient()
const txt=(v:any)=>String(v??'')
const n=(v:any)=>Number(v||0)
const money=(v:any)=>`₹ ${n(v).toFixed(2)}`
const human=(v:any)=>txt(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function PurchaseTransactionDetail({id}:{id:string}){
 const [row,setRow]=useState<Row|null>(null),[supplier,setSupplier]=useState<Row|null>(null),[lines,setLines]=useState<Row[]>([]),[items,setItems]=useState<Record<string,Row>>({}),[units,setUnits]=useState<Record<string,Row>>({}),[receipt,setReceipt]=useState<Row|null>(null),[receiptLines,setReceiptLines]=useState<Row[]>([]),[returns,setReturns]=useState<Row[]>([]),[returnLines,setReturnLines]=useState<Row[]>([]),[attachments,setAttachments]=useState<Row[]>([])
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[openReturn,setOpenReturn]=useState(false),[openReceipt,setOpenReceipt]=useState(false),[receiptDraft,setReceiptDraft]=useState<Row[]>([])
 const [returnLine,setReturnLine]=useState(''),[returnQty,setReturnQty]=useState(''),[source,setSource]=useState('rejected_receipt'),[reason,setReason]=useState('Damage / quality issue'),[credit,setCredit]=useState('0')
 const load=async()=>{
  const {data,error:e}=await db().from('purchases').select('*').eq('id',id).single();if(e){setError(true);setMessage(e.message);return}setRow(data)
  if(data?.supplier_id){const {data:s}=await db().from('suppliers').select('id,business_code,business_name,phone,email,address').eq('id',data.supplier_id).single();setSupplier(s??null)}
  const {data:pl}=await db().from('purchase_lines').select('id,item_id,billed_quantity,unit_id,unit_rate,line_total,line_notes,notes').eq('purchase_id',id).order('created_at');setLines(pl??[])
  const ids=[...new Set((pl??[]).map(x=>txt(x.item_id)).filter(Boolean))];if(ids.length){const {data:it}=await db().from('items').select('id,item_code,business_code,name').in('id',ids);setItems(Object.fromEntries((it??[]).map(x=>[txt(x.id),x])))}
  const uids=[...new Set((pl??[]).map(x=>txt(x.unit_id)).filter(Boolean))];if(uids.length){const {data:u}=await db().from('units').select('id,name,symbol').in('id',uids);setUnits(Object.fromEntries((u??[]).map(x=>[txt(x.id),x])))}
  const {data:rc}=await db().from('purchase_receipts').select('id,status,received_at,notes').eq('purchase_id',id).order('received_at',{ascending:false}).limit(1);const r=rc?.[0]??null;setReceipt(r)
  if(r){const {data:rl}=await db().from('purchase_receipt_lines').select('id,purchase_line_id,received_quantity,accepted_quantity,rejected_quantity,replacement_quantity,received_batch_date,expiry_date,best_before_date,notes').eq('receipt_id',r.id).order('id');setReceiptLines(rl??[])}else setReceiptLines([])
  const {data:rr}=await db().from('purchase_returns').select('id,business_code,return_date,reason,status,supplier_agreed,credit_amount,notes').eq('purchase_id',id).neq('status','cancelled').order('return_date',{ascending:false});setReturns(rr??[])
  if(rr?.length){const {data:rl}=await db().from('purchase_return_lines').select('id,purchase_return_id,purchase_line_id,quantity,unit_id,reason,return_source').in('purchase_return_id',rr.map(x=>x.id)).order('id');setReturnLines(rl??[])}else setReturnLines([])
  const {data:att}=await db().from('purchase_attachments').select('id,file_name,mime_type,file_size,created_at,storage_path').eq('purchase_id',id).order('created_at',{ascending:false});setAttachments(att??[])
 }
 useEffect(()=>{void load()},[id])
 const act=async(rpc:string,args:Row)=>{setBusy(true);setError(false);setMessage('');const {error:e}=await db().rpc(rpc,args);setBusy(false);if(e){setError(true);setMessage(e.message);return false}setMessage('Action completed successfully.');await load();return true}
 const startReceipt=()=>{setReceiptDraft(lines.map(l=>({id:l.id,item_id:l.item_id,unit_id:l.unit_id,billed_quantity:l.billed_quantity,received_quantity:l.billed_quantity,accepted_quantity:l.billed_quantity,rejected_quantity:0,replacement_quantity:0,inspection_notes:''})));setOpenReceipt(true)}
 const recordReceipt=async()=>{for(const l of receiptDraft){const received=n(l.received_quantity),accepted=n(l.accepted_quantity),rejected=n(l.rejected_quantity);if(received<=0||accepted<0||rejected<0||accepted+rejected!==received){setError(true);setMessage('For every item, Received must be greater than zero and Accepted + Rejected must equal Received.');return}}
  const ok=await act('receive_purchase',{p_purchase_id:id,p_lines:receiptDraft.map(l=>({purchase_line_id:l.id,received_quantity:n(l.received_quantity),accepted_quantity:n(l.accepted_quantity),rejected_quantity:n(l.rejected_quantity),replacement_quantity:0,received_batch_date:new Date().toISOString().slice(0,10),notes:txt(l.inspection_notes)||null})),p_received_at:new Date().toISOString()});if(ok){setOpenReceipt(false);setReceiptDraft([])}
 }
 const returnable:Row[]=lines.map(l=>{const rs=receiptLines.filter(x=>txt(x.purchase_line_id)===txt(l.id));const rejected=rs.reduce((s,x)=>s+n(x.rejected_quantity),0);const returnedRejected=returnLines.filter(x=>txt(x.purchase_line_id)===txt(l.id)&&txt(x.return_source)==='rejected_receipt').reduce((s,x)=>s+n(x.quantity),0);return {...l,rejected,availableRejected:Math.max(0,rejected-returnedRejected)}})
 const recordReturn=async()=>{if(!returnLine||n(returnQty)<=0){setError(true);setMessage('Select an item and enter a return quantity.');return}const ok=await act('record_supplier_return',{p_purchase_id:id,p_return_date:new Date().toISOString().slice(0,10),p_reason:reason,p_lines:[{purchase_line_id:returnLine,quantity:n(returnQty),return_source:source,reason}],p_credit_amount:n(credit),p_supplier_agreed:true,p_notes:source==='rejected_receipt'?'Rejected or damaged receipt quantity returned to supplier.':'Accepted stock returned to supplier.'});if(ok){setOpenReturn(false);setReturnQty('');setCredit('0')}}
 if(!row)return <section className="page-panel"><p>{message||'Loading purchase…'}</p></section>
 const workflow=txt(row.workflow_status)
 const canComplete=['inspected_stock','inspected_invoice','partial_returned','returned'].includes(workflow)
 const lineSubtotal=lines.reduce((s,l)=>s+n(l.line_total),0)
 const purchaseTotal=Math.max(0,lineSubtotal-n(row.discount_amount)+n(row.delivery_charge)+n(row.transport_charge)+n(row.loading_charge)+n(row.unloading_charge)+n(row.packing_charge)+n(row.other_charge)+n(row.tax_amount))
 return <section className="page-panel">
  <div className="master-header"><div><div className="section-label">Mane Masala</div><h1>{txt(row.business_code)||'Purchase'}</h1><p className="page-intro">A simple review of this supplier purchase: who supplied it, what was bought, what arrived, what was accepted, and what happens next.</p></div><Link className="secondary-button" href="/purchases">Back to purchases</Link></div>
  <div className="purchase-flow"><span className="flow-done">1. Purchase</span><span className={receipt?'flow-done':''}>2. Receive & inspect</span><span className={workflow==='completed'?'flow-done':''}>3. Complete</span><span>4. Pay supplier</span></div>
  <div className="console-panel"><div className="panel-heading"><h2>Purchase information</h2><span className="status-pill">{human(workflow)}</span></div><div className="form-grid purchase-summary-grid"><div className="field"><span>Supplier</span><input readOnly value={supplier?`${txt(supplier.business_name)}${supplier.business_code?` — ${supplier.business_code}`:''}`:'Supplier information unavailable'}/></div><div className="field"><span>Purchase date</span><input readOnly value={txt(row.purchase_date)}/></div><div className="field"><span>Supplier invoice / bill no.</span><input readOnly value={txt(row.supplier_invoice_number)||'Not provided'}/></div><div className="field"><span>Purchase source</span><input readOnly value={human(row.purchase_source)||'Other'}/></div><div className="field"><span>Bill total</span><input readOnly value={money(purchaseTotal)}/></div><div className="field"><span>Payment status</span><input readOnly value={human(row.financial_status)||'Unpaid'}/></div><div className="field"><span>Purchase status</span><input readOnly value={human(workflow)}/></div><div className="field"><span>Notes</span><input readOnly value={txt(row.notes)||'—'}/></div></div></div>
  <div className="console-panel"><div className="panel-heading"><h2>Items purchased</h2><span>{lines.length} item{lines.length===1?'':'s'}</span></div><div className="table-wrap purchase-table-wrap" style={{width:'100%',overflowX:'auto'}}><table style={{width:'max-content',minWidth:'100%'}}><thead><tr><th>SL</th><th>Item</th><th>Quantity</th><th>Unit</th><th>Rate</th><th>Line total</th></tr></thead><tbody>{lines.map((l,i)=>{const it=items[txt(l.item_id)]||{},u=units[txt(l.unit_id)]||{};return <tr key={txt(l.id)}><td>{i+1}</td><td><strong>{txt(it.item_code||it.business_code)}</strong> — {txt(it.name)}</td><td>{txt(l.billed_quantity)}</td><td>{txt(u.symbol||u.name)||'—'}</td><td>{l.unit_rate==null?'—':money(l.unit_rate)}</td><td>{money(l.line_total)}</td></tr>})}</tbody></table></div></div>
  <div className="console-panel"><div className="panel-heading"><h2>Receive & inspect</h2><span>{receipt?human(receipt.status):'Not received yet'}</span></div>{!receipt?<><p className="page-intro">The goods have not been recorded as physically received yet.</p><button className="primary-button" type="button" disabled={busy} onClick={startReceipt}>Receive & inspect goods</button></>:<div className="table-wrap purchase-table-wrap" style={{width:'100%',overflowX:'auto'}}><table style={{width:'max-content',minWidth:'100%'}}><thead><tr><th>Item</th><th>Received</th><th>Accepted into stock</th><th>Rejected / damaged</th><th>Replacement</th><th>Batch date</th></tr></thead><tbody>{receiptLines.map(rl=>{const pl=lines.find(x=>txt(x.id)===txt(rl.purchase_line_id))||{},it=items[txt(pl.item_id)]||{},u=units[txt(pl.unit_id)]||{};return <tr key={txt(rl.id)}><td>{txt(it.item_code||it.business_code)} — {txt(it.name)}</td><td>{txt(rl.received_quantity)} {txt(u.symbol)}</td><td>{txt(rl.accepted_quantity)} {txt(u.symbol)}</td><td>{txt(rl.rejected_quantity)} {txt(u.symbol)}</td><td>{txt(rl.replacement_quantity)} {txt(u.symbol)}</td><td>{txt(rl.received_batch_date)||'—'}</td></tr>})}</tbody></table></div>}{receipt&&<p className="muted">Accepted quantity becomes usable stock. Rejected or damaged quantity does not.</p>}</div>
  <div className="console-panel"><div className="panel-heading"><h2>Damages, returns & supplier credit</h2><span>{returns.length} return{returns.length===1?'':'s'}</span></div>{returnable.some(x=>x.availableRejected>0)&&<div className="form-status"><strong>Rejected / damaged goods are awaiting a return decision.</strong> They are not usable stock.</div>}{returns.length>0&&<div className="table-wrap purchase-table-wrap" style={{width:'100%',overflowX:'auto',marginTop:12}}><table style={{width:'max-content',minWidth:'100%'}}><thead><tr><th>Return</th><th>Date</th><th>Item</th><th>Qty</th><th>Reason</th><th>Credit</th></tr></thead><tbody>{returns.map(r=>returnLines.filter(x=>txt(x.purchase_return_id)===txt(r.id)).map(x=>{const pl=lines.find(p=>txt(p.id)===txt(x.purchase_line_id))||{},it=items[txt(pl.item_id)]||{};return <tr key={`${txt(r.id)}-${txt(x.id)}`}><td>{txt(r.business_code)||'Supplier return'}</td><td>{txt(r.return_date)}</td><td>{txt(it.item_code||it.business_code)} — {txt(it.name)}</td><td>{txt(x.quantity)}</td><td>{txt(x.reason||r.reason)||'—'}</td><td>{money(r.credit_amount)}</td></tr>}))}</tbody></table></div>}<div className="purchase-actions" style={{justifyContent:'flex-start'}}><button className="secondary-button" type="button" disabled={busy||!receipt} onClick={()=>setOpenReturn(true)}>Record damage / supplier return</button></div><p className="muted">Use this only when goods are actually being returned to the supplier. The original purchase remains unchanged.</p></div>
  <div className="console-panel"><div className="panel-heading"><h2>Invoice / supporting documents</h2><span>{attachments.length} attached</span></div>{attachments.length===0?<p className="page-intro">No invoice or purchase slip is attached.</p>:<div className="table-wrap purchase-table-wrap" style={{width:'100%',overflowX:'auto'}}><table style={{width:'max-content',minWidth:'100%'}}><thead><tr><th>Document</th><th>Type</th><th>Size</th><th>Added</th></tr></thead><tbody>{attachments.map(a=><tr key={txt(a.id)}><td>{txt(a.file_name)}</td><td>{txt(a.mime_type)||'—'}</td><td>{a.file_size?`${Math.round(n(a.file_size)/1024)} KB`:'—'}</td><td>{txt(a.created_at)}</td></tr>)}</tbody></table></div>}</div>
  <div className="console-panel"><div className="panel-heading"><h2>Next step</h2></div>{workflow==='completed'?<><p className="page-intro"><strong>Purchase is complete.</strong> If money is still due, continue to supplier payment.</p><Link className="primary-button" href="/payments">Proceed to supplier payment</Link></>:canComplete?<><p className="page-intro"><strong>Review complete.</strong> Confirm the received, accepted and rejected quantities before completing this purchase.</p><button className="primary-button" type="button" disabled={busy} onClick={()=>void act('complete_purchase_inspection',{p_purchase_id:id})}>{busy?'Processing…':'Complete purchase'}</button></>:<><p className="page-intro">The next step is to receive and inspect the physical goods.</p><button className="primary-button" type="button" disabled={busy} onClick={startReceipt}>Receive & inspect goods</button></>}</div>
  {message&&<p className={`form-status${error?' form-status-error':''}`} role="alert">{message}</p>}
  {openReceipt&&<div className="modal-backdrop"><div className="modal-card purchase-modal"><div className="modal-header"><div><h3>Receive & inspect goods</h3><p className="muted">Enter what physically arrived. Only accepted quantity enters usable stock.</p></div><button className="secondary-button" type="button" onClick={()=>setOpenReceipt(false)}>Cancel</button></div><div className="table-wrap purchase-table-wrap" style={{width:'100%',overflowX:'auto'}}><table style={{width:'max-content',minWidth:'100%'}}><thead><tr><th>Item</th><th>Billed</th><th>Received</th><th>Accepted</th><th>Rejected / damaged</th><th>Inspection notes</th></tr></thead><tbody>{receiptDraft.map((l,i)=>{const it=items[txt(l.item_id)]||{},u=units[txt(l.unit_id)]||{};return <tr key={txt(l.id)}><td><strong>{txt(it.item_code||it.business_code)}</strong> — {txt(it.name)}<small className="muted">{txt(u.symbol)}</small></td><td>{txt(l.billed_quantity)}</td><td><input className="table-input" type="number" min="0" step="0.001" value={l.received_quantity} onChange={e=>setReceiptDraft(v=>v.map((x,n)=>n===i?{...x,received_quantity:e.target.value}:x))}/></td><td><input className="table-input" type="number" min="0" step="0.001" value={l.accepted_quantity} onChange={e=>setReceiptDraft(v=>v.map((x,n)=>n===i?{...x,accepted_quantity:e.target.value}:x))}/></td><td><input className="table-input" type="number" min="0" step="0.001" value={l.rejected_quantity} onChange={e=>setReceiptDraft(v=>v.map((x,n)=>n===i?{...x,rejected_quantity:e.target.value}:x))}/></td><td><input className="table-input" value={l.inspection_notes} onChange={e=>setReceiptDraft(v=>v.map((x,n)=>n===i?{...x,inspection_notes:e.target.value}:x))} placeholder="Optional"/></td></tr>})}</tbody></table></div><p className="muted">Example: billed 25 kg, received 24.5 kg, accepted 24 kg, rejected 0.5 kg. The 0.5 kg remains a supplier issue—not usable stock.</p><div className="purchase-actions"><button className="secondary-button" type="button" onClick={()=>setOpenReceipt(false)}>Cancel</button><button className="primary-button" type="button" disabled={busy} onClick={()=>void recordReceipt()}>{busy?'Saving…':'Record receipt & inspection'}</button></div></div></div>}
  {openReturn&&<div className="modal-backdrop"><div className="modal-card purchase-modal"><div className="modal-header"><div><h3>Record damage / supplier return</h3><p className="muted">Choose the item and quantity actually being returned. This creates a linked correction.</p></div><button className="secondary-button" type="button" onClick={()=>setOpenReturn(false)}>Cancel</button></div><div className="form-grid"><label className="field"><span>Item</span><select value={returnLine} onChange={e=>setReturnLine(e.target.value)}><option value="">Select item</option>{returnable.map(l=><option key={txt(l.id)} value={txt(l.id)}>{txt(items[txt(l.item_id)]?.item_code||items[txt(l.item_id)]?.business_code)} — {txt(items[txt(l.item_id)]?.name)}{l.availableRejected>0?` — ${l.availableRejected} rejected available`:''}</option>)}</select></label><label className="field"><span>Return type</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="rejected_receipt">Rejected / damaged at receipt</option><option value="accepted_stock">Accepted stock returned</option></select></label><label className="field"><span>Quantity</span><input type="number" min="0" step="0.001" value={returnQty} onChange={e=>setReturnQty(e.target.value)} placeholder="Enter quantity"/></label><label className="field"><span>Reason</span><select value={reason} onChange={e=>setReason(e.target.value)}><option>Damage / quality issue</option><option>Wrong item</option><option>Expiry / freshness</option><option>Shortage / discrepancy</option><option>Other</option></select></label><label className="field"><span>Supplier credit (₹)</span><input type="number" min="0" step="0.01" value={credit} onChange={e=>setCredit(e.target.value)} placeholder="0 if no credit agreed"/></label></div><div className="purchase-actions"><button className="secondary-button" type="button" onClick={()=>setOpenReturn(false)}>Cancel</button><button className="primary-button" type="button" disabled={busy} onClick={()=>void recordReturn()}>{busy?'Saving…':'Record supplier return'}</button></div></div></div>}
 </section>
}
