'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Row = Record<string, any>
const db=()=>createClient()
const txt=(v:any)=>String(v??'')
const n=(v:any)=>Number(v||0)
const money=(v:any)=>`₹ ${n(v).toFixed(2)}`

export default function PurchaseTransactionDetail({id}:{id:string}){
 const [row,setRow]=useState<Row|null>(null),[lines,setLines]=useState<Row[]>([]),[items,setItems]=useState<Record<string,Row>>({}),[receipt,setReceipt]=useState<Row|null>(null),[receiptLines,setReceiptLines]=useState<Row[]>([]),[returns,setReturns]=useState<Row[]>([]),[returnLines,setReturnLines]=useState<Row[]>([]),[attachments,setAttachments]=useState<Row[]>([])
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[openReturn,setOpenReturn]=useState(false)
 const [returnLine,setReturnLine]=useState(''),[returnQty,setReturnQty]=useState(''),[source,setSource]=useState('rejected_receipt'),[reason,setReason]=useState('Damage / quality issue'),[credit,setCredit]=useState('0')
 const load=async()=>{
  const {data,error:e}=await db().from('purchases').select('*').eq('id',id).single();if(e){setError(true);setMessage(e.message);return}setRow(data)
  const {data:pl}=await db().from('purchase_lines').select('id,item_id,billed_quantity,unit_id,unit_rate,line_total,line_notes,notes').eq('purchase_id',id).order('id');setLines(pl??[])
  const ids=[...new Set((pl??[]).map(x=>txt(x.item_id)).filter(Boolean))];if(ids.length){const {data:it}=await db().from('items').select('id,item_code,business_code,name').in('id',ids);setItems(Object.fromEntries((it??[]).map(x=>[txt(x.id),x])))}
  const {data:rc}=await db().from('purchase_receipts').select('id,status,received_at,notes').eq('purchase_id',id).order('received_at',{ascending:false}).limit(1);const r=rc?.[0]??null;setReceipt(r)
  if(r){const {data:rl}=await db().from('purchase_receipt_lines').select('id,purchase_line_id,received_quantity,accepted_quantity,rejected_quantity,replacement_quantity,received_batch_date,expiry_date,best_before_date,notes').eq('receipt_id',r.id).order('id');setReceiptLines(rl??[])}else setReceiptLines([])
  const {data:rr}=await db().from('purchase_returns').select('id,business_code,return_date,reason,status,supplier_agreed,credit_amount,notes').eq('purchase_id',id).neq('status','cancelled').order('return_date',{ascending:false});setReturns(rr??[])
  if(rr?.length){const {data:rl}=await db().from('purchase_return_lines').select('id,purchase_return_id,purchase_line_id,quantity,unit_id,reason,return_source').in('purchase_return_id',rr.map(x=>x.id)).order('id');setReturnLines(rl??[])}else setReturnLines([])
  const {data:att}=await db().from('purchase_attachments').select('id,file_name,mime_type,file_size,created_at,storage_path').eq('purchase_id',id).order('created_at',{ascending:false});setAttachments(att??[])
 }
 useEffect(()=>{void load()},[id])
 const act=async(rpc:string,args:Row)=>{setBusy(true);setError(false);setMessage('');const {error:e}=await db().rpc(rpc,args);setBusy(false);if(e){setError(true);setMessage(e.message);return}setMessage('Action completed successfully.');await load()}
 const returnable=lines.map(l=>{const rs=receiptLines.filter(x=>txt(x.purchase_line_id)===txt(l.id));const rejected=rs.reduce((s,x)=>s+n(x.rejected_quantity),0);const returnedRejected=returnLines.filter(x=>txt(x.purchase_line_id)===txt(l.id)&&txt(x.return_source)==='rejected_receipt').reduce((s,x)=>s+n(x.quantity),0);return {...l,rejected,availableRejected:Math.max(0,rejected-returnedRejected)}})
 const recordReturn=async()=>{if(!returnLine||n(returnQty)<=0){setError(true);setMessage('Select an item and enter a return quantity.');return}setBusy(true);setError(false);setMessage('');const {error:e}=await db().rpc('record_supplier_return',{p_purchase_id:id,p_return_date:new Date().toISOString().slice(0,10),p_reason:reason,p_lines:[{purchase_line_id:returnLine,quantity:n(returnQty),return_source:source,reason}],p_credit_amount:n(credit),p_supplier_agreed:true,p_notes:source==='rejected_receipt'?'Rejected or damaged receipt quantity returned to supplier.':'Accepted stock returned to supplier.'});setBusy(false);if(e){setError(true);setMessage(e.message);return}setOpenReturn(false);setReturnQty('');setCredit('0');setMessage('Supplier return recorded. Original purchase history is preserved.');await load()}
 if(!row)return <section className="page-panel"><p>{message||'Loading purchase…'}</p></section>
 const fields=Object.entries(row).filter(([k])=>!['id','created_at','updated_at','created_by'].includes(k))
 const workflow=txt(row.workflow_status)
 const canComplete=['inspected_stock','inspected_invoice','partial_returned','returned'].includes(workflow)
 return <section className="page-panel">
  <div className="master-header"><div><div className="section-label">Mane Masala</div><h1>{txt(row.business_code)||'Purchase'}</h1><p className="page-intro">Review what was bought, what arrived, what was accepted, and what needs to happen next.</p></div><Link className="secondary-button" href="/purchases">Back to purchases</Link></div>
  <div className="purchase-flow"><span className="flow-active">1 Purchase</span><span className={receipt?'flow-active':''}>2 Receive & inspect</span><span>3 Complete</span><span>4 Pay supplier</span></div>
  <div className="console-panel"><div className="panel-heading"><h2>Purchase summary</h2><span>{workflow.replaceAll('_',' ')}</span></div><div className="form-grid">{fields.map(([k,v])=><div className="field" key={k}><span>{k.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())}</span><input readOnly value={typeof v==='object'&&v!==null?JSON.stringify(v):txt(v)}/></div>)}</div></div>
  <div className="console-panel"><div className="panel-heading"><h2>Items purchased</h2><span>{lines.length} item{lines.length===1?'':'s'}</span></div><div className="table-wrap"><table><thead><tr><th>SL</th><th>Item</th><th>Billed Qty</th><th>Rate</th><th>Line Total</th></tr></thead><tbody>{lines.map((l,i)=>{const it=items[txt(l.item_id)]||{};return <tr key={txt(l.id)}><td>{i+1}</td><td><strong>{txt(it.item_code||it.business_code)}</strong> — {txt(it.name)}</td><td>{txt(l.billed_quantity)}</td><td>{money(l.unit_rate)}</td><td>{money(l.line_total)}</td></tr>})}</tbody></table></div></div>
  <div className="console-panel"><div className="panel-heading"><h2>Receive & inspect</h2><span>{receipt?txt(receipt.status).replaceAll('_',' '):'Not received yet'}</span></div>{!receipt?<p className="page-intro">No physical receipt has been recorded yet. Use the Purchase workflow to receive and inspect the goods.</p>:<div className="table-wrap"><table><thead><tr><th>Item</th><th>Received</th><th>Accepted into stock</th><th>Rejected / damaged</th><th>Replacement</th><th>Batch date</th></tr></thead><tbody>{receiptLines.map(rl=>{const pl=lines.find(x=>txt(x.id)===txt(rl.purchase_line_id))||{};const it=items[txt(pl.item_id)]||{};return <tr key={txt(rl.id)}><td>{txt(it.item_code||it.business_code)} — {txt(it.name)}</td><td>{txt(rl.received_quantity)}</td><td>{txt(rl.accepted_quantity)}</td><td>{txt(rl.rejected_quantity)}</td><td>{txt(rl.replacement_quantity)}</td><td>{txt(rl.received_batch_date)||'—'}</td></tr>})}</tbody></table></div>}{receipt&&<p className="muted" style={{marginTop:12}}>Rejected or damaged goods do not become usable stock. Accepted goods do.</p>}</div>
  <div className="console-panel"><div className="panel-heading"><h2>Damages & supplier returns</h2><span>{returns.length} return{returns.length===1?'':'s'} recorded</span></div>{returnable.some(x=>x.availableRejected>0)&&<div className="form-status"><strong>Rejected / damaged quantity is waiting for a return decision.</strong> It is not in usable stock.</div>}{returns.length>0&&<div className="table-wrap" style={{marginTop:12}}><table><thead><tr><th>Return</th><th>Date</th><th>Item</th><th>Qty</th><th>Reason</th><th>Credit</th></tr></thead><tbody>{returns.map(r=>returnLines.filter(x=>txt(x.purchase_return_id)===txt(r.id)).map(x=>{const pl=lines.find(p=>txt(p.id)===txt(x.purchase_line_id))||{};const it=items[txt(pl.item_id)]||{};return <tr key={`${txt(r.id)}-${txt(x.id)}`}><td>{txt(r.business_code)||'Supplier return'}</td><td>{txt(r.return_date)}</td><td>{txt(it.item_code||it.business_code)} — {txt(it.name)}</td><td>{txt(x.quantity)}</td><td>{txt(x.reason||r.reason)||'—'}</td><td>{money(r.credit_amount)}</td></tr>}))}</tbody></table></div>}<div className="purchase-actions" style={{justifyContent:'flex-start'}}><button className="secondary-button" type="button" disabled={busy} onClick={()=>setOpenReturn(true)}>Record damage / supplier return</button></div><p className="muted">For rejected goods, this records the supplier return without touching inventory. For accepted stock, the return removes physical stock through the inventory ledger.</p></div>
  <div className="console-panel"><div className="panel-heading"><h2>Bill & supporting documents</h2><span>{attachments.length} attached</span></div>{attachments.length===0?<p className="page-intro">No invoice or purchase slip is attached.</p>:<div className="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Size</th><th>Added</th></tr></thead><tbody>{attachments.map(a=><tr key={txt(a.id)}><td>{txt(a.file_name)}</td><td>{txt(a.mime_type)||'—'}</td><td>{a.file_size?`${Math.round(n(a.file_size)/1024)} KB`:'—'}</td><td>{txt(a.created_at)}</td></tr>)}</tbody></table></div>}</div>
  <div className="console-panel"><div className="panel-heading"><h2>Next action</h2></div>{workflow==='completed'?<><p className="page-intro"><strong>Purchase completed.</strong> Continue to supplier payment when payment is due.</p><Link className="primary-button" href="/payments">Proceed to supplier payment</Link></>:canComplete?<><p className="page-intro">Check the receipt, accepted stock and rejected / damaged quantities before completing the purchase.</p><button className="primary-button" type="button" disabled={busy} onClick={()=>void act('complete_purchase_inspection',{p_purchase_id:id})}>{busy?'Processing…':'Complete purchase'}</button></>:<><p className="page-intro">The physical receipt and inspection still need to be recorded.</p><Link className="secondary-button" href="/purchases">Open Purchase workflow</Link></>}</div>
  {message&&<p className={`form-status${error?' form-status-error':''}`} role="alert">{message}</p>}
  {openReturn&&<div className="modal-backdrop"><div className="modal-card purchase-modal"><div className="modal-header"><div><h3>Record damage / supplier return</h3><p className="muted">The original purchase stays unchanged. This creates a linked correction.</p></div><button className="secondary-button" type="button" onClick={()=>setOpenReturn(false)}>Cancel</button></div><div className="form-grid"><label className="field"><span>Item</span><select value={returnLine} onChange={e=>setReturnLine(e.target.value)}><option value="">Select item</option>{returnable.map(l=><option key={txt(l.id)} value={txt(l.id)}>{txt(items[txt(l.item_id)]?.item_code||items[txt(l.item_id)]?.business_code)} — {txt(items[txt(l.item_id)]?.name)}{l.availableRejected>0?` — ${l.availableRejected} rejected available`:''}</option>)}</select></label><label className="field"><span>What are you returning?</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="rejected_receipt">Rejected / damaged at receipt</option><option value="accepted_stock">Accepted stock</option></select></label><label className="field"><span>Quantity</span><input type="number" min="0" step="0.001" value={returnQty} onChange={e=>setReturnQty(e.target.value)} placeholder="Quantity in item unit"/></label><label className="field"><span>Reason</span><select value={reason} onChange={e=>setReason(e.target.value)}><option>Damage / quality issue</option><option>Wrong item</option><option>Expiry / freshness</option><option>Shortage / discrepancy</option><option>Other</option></select></label><label className="field"><span>Supplier credit</span><input type="number" min="0" step="0.01" value={credit} onChange={e=>setCredit(e.target.value)} placeholder="₹ 0 if no credit agreed yet"/></label></div><div className="purchase-actions"><button className="secondary-button" type="button" onClick={()=>setOpenReturn(false)}>Cancel</button><button className="primary-button" type="button" disabled={busy} onClick={()=>void recordReturn()}>{busy?'Processing…':'Approve & record return'}</button></div></div></div>}
 </section>
}
