'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function RecipeProductionCreate(){
  const [outputId,setOutputId]=useState('');const [ingredientId,setIngredientId]=useState('');const [name,setName]=useState('');const [ingredientQty,setIngredientQty]=useState('');const [expectedQty,setExpectedQty]=useState('');const [productionQty,setProductionQty]=useState('');const [message,setMessage]=useState('');const [items,setItems]=useState<any[]>([])
  useEffect(()=>{createClient().from('items').select('id,name,base_unit_id').eq('is_active',true).order('name').then(({data})=>setItems(data??[]))},[])
  const create=async()=>{const sb=createClient();const out=items.find(x=>x.id===outputId),ing=items.find(x=>x.id===ingredientId);if(!out||!ing||!name||!ingredientQty||!expectedQty){setMessage('Recipe name, output, ingredient and quantities are required.');return}const {data:recipe,error:e1}=await sb.from('recipes').insert({output_item_id:out.id,name,status:'active'}).select().single();if(e1){setMessage(e1.message);return}const {data:version,error:e2}=await sb.from('recipe_versions').insert({recipe_id:recipe.id,version_number:1,expected_output_quantity:Number(expectedQty),output_unit_id:out.base_unit_id,status:'active',effective_from:new Date().toISOString().slice(0,10)}).select().single();if(e2){setMessage(e2.message);return}const {error:e3}=await sb.from('recipe_lines').insert({recipe_version_id:version.id,ingredient_item_id:ing.id,quantity:Number(ingredientQty),unit_id:ing.base_unit_id,sequence_number:1});if(e3){setMessage(e3.message);return}const {data:batch,error:e4}=await sb.from('production_batches').insert({recipe_version_id:version.id,output_item_id:out.id,planned_output_quantity:Number(productionQty||expectedQty),output_unit_id:out.base_unit_id,production_date:new Date().toISOString().slice(0,10),status:'planned',wife_approval_status:'pending'}).select().single();setMessage(e4?.message??`Recipe and production batch created: ${batch?.id}`)}
  return <div className="console-panel"><div className="panel-heading"><h2>New recipe + production batch</h2></div><div className="form-grid"><input placeholder="Recipe name" value={name} onChange={e=>setName(e.target.value)}/><select value={outputId} onChange={e=>setOutputId(e.target.value)}><option value="">Output item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={ingredientId} onChange={e=>setIngredientId(e.target.value)}><option value="">Ingredient</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" placeholder="Ingredient quantity" value={ingredientQty} onChange={e=>setIngredientQty(e.target.value)}/><input type="number" placeholder="Expected output" value={expectedQty} onChange={e=>setExpectedQty(e.target.value)}/><input type="number" placeholder="Production quantity" value={productionQty} onChange={e=>setProductionQty(e.target.value)}/><button onClick={create}>Create recipe & batch</button></div><p className="form-status">{message}</p></div>
}
