'use client'

import { useEffect, useState, type ReactNode } from 'react'
import { createClient } from '@/lib/supabase/client'
import DataTable from '@/components/data-table'

type Row = Record<string, any>
const db = () => createClient()
const today = () => new Date().toISOString().slice(0, 10)
const txt = (v: any) => String(v ?? '')
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Status({ message, error }: { message: string; error: boolean }) { return message ? <p className={`form-status${error ? ' form-status-error' : ''}`} role="alert">{message}</p> : null }

export default function SalesInvoicesConsoleV2() {
  const [orders,setOrders]=useState<Row[]>([]),[dispatches,setDispatches]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[oid,setOid]=useState(''),[method,setMethod]=useState('own_delivery'),[dispatchId,setDispatchId]=useState(''),[lines,setLines]=useState<Row[]>([]),[invoiceRows,setInvoiceRows]=useState<Row[]>([]),[selectedInvoiceId,setSelectedInvoiceId]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(false),[refreshToken,setRefreshToken]=useState(0)
  const load=async()=>{const[o,d,i]=await Promise.all([db().from('orders').select('*').order('order_date',{ascending:false}),db().from('dispatches').select('*').order('dispatch_date',{ascending:false}),db().from('items').select('*')]);setOrders(o.data??[]);setDispatches(d.data??[]);setItems(i.data??[]);setInvoiceRows((await db().from('invoices').select('id,invoice_number,business_code,invoice_date,total_amount,status').order('created_at',{ascending:false})).data??[])}
  useEffect(()=>{void load()},[])
  const chooseOrder=async(id:string)=>{setOid(id);setDispatchId('');setMessage('');setError(false);if(!id){setLines([]);return}const{data}=await db().from('order_lines').select('id,item_id,ordered_quantity,dispatched_quantity').eq('order_id',id);setLines((data??[]).map(x=>({...x,quantity:Math.max(0,Number(x.ordered_quantity)-Number(x.dispatched_quantity||0))}))) }
  const dispatch=async()=>{const selected=lines.filter(x=>Number(x.quantity)>0).map(x=>({order_line_id:x.id,quantity:Number(x.quantity)}));if(!oid||!selected.length){setError(true);setMessage('Select an order and at least one dispatch quantity.');return}const{error:e}=await db().rpc('dispatch_order',{p_order_id:oid,p_dispatch_date:today(),p_method:method,p_lines:selected});if(e){setError(true);setMessage(e.message);return}setError(false);setMessage('Dispatch completed. Select the actual dispatch below before creating the Sale & Invoice.');await load();setRefreshToken(v=>v+1)}
  const invoice=async()=>{if(!dispatchId){setError(true);setMessage('Select the actual completed dispatch.');return}const{error:e}=await db().rpc('create_sale_invoice',{p_dispatch_id:dispatchId});if(e){setError(true);setMessage(e.message);return}setError(false);setMessage('Sale and Invoice created. Any order advance is now shown as advance and deducted from amount due.');const{data:sale}=await db().from('sales').select('id').eq('dispatch_id',dispatchId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(sale){const{data:inv}=await db().from('invoices').select('id').eq('sale_id',sale.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(inv)setSelectedInvoiceId(txt(inv.id))}await load();setRefreshToken(v=>v+1)}
  return <section className="page-panel"><div className="section-label">Mane Masala</div><div className="master-header"><div><h1>Sales & Invoices</h1><p className="page-intro">Dispatch is the physical stock movement. Sale and Invoice are created only from the completed dispatch, so stock is not reduced twice.</p></div></div>
    <div className="console-panel"><div className="panel-heading"><h2>1. Dispatch</h2></div><div className="form-grid"><Field label="Order"><select value={oid} onChange={e=>chooseOrder(e.target.value)}><option value="">Select ready order</option>{orders.filter(o=>['confirmed','in_production','ready','partially_dispatched'].includes(txt(o.status))).map(o=><option key={txt(o.id)} value={txt(o.id)}>{txt(o.business_code)} — {txt(o.status)}</option>)}</select></Field><Field label="Dispatch method"><select value={method} onChange={e=>setMethod(e.target.value)}><option value="own_delivery">Own delivery</option><option value="customer_pickup">Customer pickup</option><option value="courier">Courier</option><option value="transport">Transport</option><option value="other">Other</option></select></Field></div>{lines.map((l,i)=>{const it=items.find(x=>txt(x.id)===txt(l.item_id));return <div className="purchase-line" key={txt(l.id)}><div className="field"><span>Item</span><div><strong>{txt(it?.item_code)}</strong> — {txt(it?.name)}</div></div><Field label="Remaining"><input value={String(Math.max(0,Number(l.ordered_quantity)-Number(l.dispatched_quantity||0)))} readOnly/></Field><Field label="Dispatch quantity"><input type="number" min="0" step="0.001" value={l.quantity} onChange={e=>setLines(v=>v.map((z,n)=>n===i?{...z,quantity:e.target.value}:z))}/></Field></div>})}<div className="purchase-actions"><button className="secondary-button" type="button" onClick={()=>{setOid('');setLines([]);setDispatchId('');setMessage('');setError(false)}}>Clear</button><button className="primary-button" type="button" onClick={dispatch}>Dispatch selected quantities</button></div></div>
    <div className="console-panel"><div className="panel-heading"><h2>2. Create Sale & Invoice</h2></div><Field label="Completed dispatch"><select value={dispatchId} onChange={e=>setDispatchId(e.target.value)}><option value="">Select actual dispatched record</option>{dispatches.filter(d=>txt(d.status)==='dispatched').map(d=><option key={txt(d.id)} value={txt(d.id)}>{txt(d.business_code)} — {txt(d.dispatch_date)}</option>)}</select></Field><div className="purchase-actions"><button className="primary-button" type="button" onClick={invoice}>Create Sale & Invoice</button></div><Status message={message} error={error}/><p className="muted">Invoice shows total, advance applied and amount due. Stock is not reduced again at invoice creation.</p></div>
    <div className="console-panel"><div className="panel-heading"><div><h2>3. Invoice actions</h2><span>Open the saved invoice as a PDF, download it, or open it for printing.</span></div></div><Field label="Saved invoice"><select value={selectedInvoiceId} onChange={e=>setSelectedInvoiceId(e.target.value)}><option value="">Select invoice</option>{invoiceRows.map(inv=><option key={txt(inv.id)} value={txt(inv.id)}>{txt(inv.invoice_number||inv.business_code)} — {txt(inv.invoice_date)} — Rs. {Number(inv.total_amount||0).toFixed(2)}</option>)}</select></Field><div className="purchase-actions"><button className="secondary-button" type="button" disabled={!selectedInvoiceId} onClick={()=>window.open(`/api/invoices/${selectedInvoiceId}/pdf`,'_blank','noopener,noreferrer')}>View Invoice / PDF</button><button className="secondary-button" type="button" disabled={!selectedInvoiceId} onClick={()=>window.open(`/api/invoices/${selectedInvoiceId}/pdf?download=1`,'_blank','noopener,noreferrer')}>Download PDF</button><button className="primary-button" type="button" disabled={!selectedInvoiceId} onClick={()=>window.open(`/api/invoices/${selectedInvoiceId}/pdf`,'_blank','noopener,noreferrer')}>Print</button></div></div>
    <div className="console-panel"><div className="panel-heading"><h2>Dispatches</h2></div><DataTable table="dispatches" refreshToken={refreshToken}/></div><div className="console-panel"><div className="panel-heading"><h2>Sales</h2></div><DataTable table="sales" refreshToken={refreshToken}/></div><div className="console-panel"><div className="panel-heading"><h2>Invoices</h2></div><DataTable table="invoices" refreshToken={refreshToken}/></div>
  </section>
}
