import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const esc = (v: unknown) => String(v ?? '').replace(/\/g, '\\').replace(/(/g, '\(').replace(/)/g, '\)')
const text = (v: unknown) => String(v ?? '').replace(/[₹]/g, 'Rs. ').replace(/[—–]/g, '-').replace(/•/g, '|')
const money = (v: unknown) => `Rs. ${Number(v || 0).toFixed(2)}`
const num = (v: unknown) => Number(v || 0)
const fyFor = (date: string, startMonth = 4, startDay = 1) => {
  const d = new Date(date + 'T00:00:00'); const y = d.getFullYear()
  const startsAfter = d.getMonth() + 1 > startMonth || (d.getMonth() + 1 === startMonth && d.getDate() >= startDay)
  const start = startsAfter ? y : y - 1; return `${start}-${String((start + 1) % 100).padStart(2, '0')}`
}
function makePdf(data: any) {
  const ops: string[]=[]; const add=(s:string)=>ops.push(s)
  const t=(x:number,y:number,v:unknown,size=10,bold=false)=>add(`BT /F${bold?2:1} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${esc(text(v))}) Tj ET`)
  const line=(x1:number,y1:number,x2:number,y2:number)=>add(`0.6 w ${x1} ${y1} m ${x2} ${y2} l S`)
  const rect=(x:number,y:number,w:number,h:number,fill=false)=>add(`${fill?'0.96 g ':'0 g '}${x} ${y} ${w} ${h} re ${fill?'f':'S'}`)
  const b=data.business||{},inv=data.invoice||{},customer=data.customer||{},lines=data.lines||[]; const hasGst=lines.some((l:any)=>num(l.tax_rate)>0)||num(inv.tax_amount)>0
  t(42,795,b.business_name||'Mane Masala',20,true);t(42,778,b.address,9);t(42,764,`Phone: ${b.phone||''}  WhatsApp: ${b.whatsapp||''}`,9);t(42,750,`Email: ${b.email||''}`,9);t(42,736,`FSSAI: ${b.fssai_number||''}`,9)
  t(440,795,'INVOICE',18,true);t(440,776,`Invoice No: ${inv.invoice_number||inv.business_code||''}`,9,true);t(440,761,`Date: ${inv.invoice_date||''}`,9);t(440,746,`FY: ${inv.financial_year||fyFor(inv.invoice_date,b.financial_year_start_month,b.financial_year_start_day)}`,9);line(42,722,553,722)
  rect(42,662,511,48,true);t(52,694,'CUSTOMER DETAILS',10,true);t(52,678,customer.name||'Customer',10,true);if(customer.phone)t(270,678,`Phone: ${customer.phone}`,9);if(customer.email)t(270,664,`Email: ${customer.email}`,9);if(customer.address)t(52,664,String(customer.address).slice(0,55),8)
  const top=632;rect(42,top-22,511,22,true);t(48,top-15,'Product',9,true);t(300,top-15,'Qty',9,true);t(350,top-15,'Rate',9,true);t(420,top-15,'GST %',9,true);t(485,top-15,'Amount',9,true)
  let y=top-40;for(const l of lines){t(48,y,String(l.item?.name||l.item?.item_code||'Item').slice(0,42),9);t(300,y,num(l.quantity).toFixed(3).replace(/\.000$/,''),9);t(350,y,money(l.selling_rate),9);if(num(l.tax_rate)>0)t(420,y,`${num(l.tax_rate).toFixed(2)}%`,9);t(485,y,money(l.line_total),9);y-=20}
  line(42,y+8,553,y+8);let ty=y-15;const tx=365;t(tx,ty,'Subtotal',9);t(485,ty,money(inv.subtotal),9);ty-=16;if(num(inv.discount_amount)>0){t(tx,ty,'Discount',9);t(480,ty,`- ${money(inv.discount_amount)}`,9);ty-=16}if(hasGst){t(tx,ty,'GST',9,true);t(485,ty,money(inv.tax_amount),9,true);ty-=16}t(tx,ty,'Total',11,true);t(480,ty,money(inv.total_amount),11,true);ty-=20;t(tx,ty,'Amount Due',10,true);t(480,ty,money(inv.amount_due),10,true)
  line(42,220,553,220);t(42,201,'Payment',10,true);t(42,186,b.accepted_payment_methods||'UPI transfer',9);t(42,171,`UPI: ${b.upi_id||''}`,9);t(42,146,b.authorised_signatory_name||'Shruthi Praveen',9,true);t(42,132,b.authorised_signatory_designation||'Founder',8);t(42,84,b.invoice_tagline||'FROM MY HOME TO YOURS - WITH RESPONSIBILITY',9,true);t(42,68,b.invoice_promise_statement||'Made to Order | Pure Ingredients | No Preservatives',8)
  const stream=ops.join('\n');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>',`<< /Length ${Buffer.byteLength(stream,'latin1')} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'];let pdf='%PDF-1.4\n';const offsets:number[]=[0];for(let i=0;i<objects.length;i++){offsets[i+1]=Buffer.byteLength(pdf,'latin1');pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`}const xref=Buffer.byteLength(pdf,'latin1');pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(pdf,'latin1')
}
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const db=await createClient();const {data:invoice,error:ie}=await db.from('invoices').select('*').eq('id',id).single();if(ie||!invoice)return new Response('Invoice not found',{status:404});const [{data:business},{data:customer},{data:lines}]=await Promise.all([db.from('business_settings').select('*').limit(1).maybeSingle(),db.from('customers').select('id,business_code,name,phone,email,address,gst_number').eq('id',invoice.billing_customer_id).maybeSingle(),db.from('sale_lines').select('id,item_id,quantity,unit_id,selling_rate,discount_amount,tax_amount,line_total,tax_rate').eq('sale_id',invoice.sale_id).order('created_at')]);const itemIds=[...new Set((lines||[]).map((l:any)=>l.item_id).filter(Boolean))],unitIds=[...new Set((lines||[]).map((l:any)=>l.unit_id).filter(Boolean))];const [{data:items},{data:units}]=await Promise.all([itemIds.length?db.from('items').select('id,item_code,business_code,name').in('id',itemIds):Promise.resolve({data:[]} as any),unitIds.length?db.from('units').select('id,name,symbol').in('id',unitIds):Promise.resolve({data:[]} as any)]);const im=new Map((items||[]).map((x:any)=>[String(x.id),x]));const um=new Map((units||[]).map((x:any)=>[String(x.id),x]));const enriched=(lines||[]).map((l:any)=>({...l,item:im.get(String(l.item_id)),unit:um.get(String(l.unit_id))}));const pdf=makePdf({invoice,business:business||{},customer,lines:enriched});const download=request.nextUrl.searchParams.get('download')==='1';const filename=`Mane-Masala-Invoice-${invoice.invoice_number||invoice.business_code||id}.pdf`;return new Response(pdf,{status:200,headers:{'Content-Type':'application/pdf','Content-Disposition':`${download?'attachment':'inline'}; filename="${filename}"`,'Content-Length':String(pdf.length),'Cache-Control':'private, no-store'}})}
