-- Phase 4 atomic workflow functions: purchase receipt, reservation, production, dispatch, sale/invoice.
-- All functions are SECURITY INVOKER, pin search_path, and require authenticated callers.

create or replace function public.receive_purchase(p_purchase_id uuid,p_lines jsonb,p_received_at timestamptz default now()) returns jsonb language plpgsql security invoker set search_path = '' as $$
declare v_receipt_id uuid:=gen_random_uuid();v_user uuid:=auth.uid();v_line jsonb;v_purchase_line public.purchase_lines%rowtype;v_received numeric;v_accepted numeric;v_rejected numeric;v_replacement numeric;v_batch_id uuid;v_outcome text;v_status text:='completed';v_count int:=0;v_workflow text;
begin
 if v_user is null then raise exception 'Authentication required';end if;select workflow_status into v_workflow from public.purchases where id=p_purchase_id for update;if v_workflow is null then raise exception 'Purchase not found';end if;if exists(select 1 from public.purchase_receipts where purchase_id=p_purchase_id and status not in ('cancelled')) then raise exception 'Purchase already has a receipt';end if;
 insert into public.purchase_receipts(id,purchase_id,received_at,received_by,status) values(v_receipt_id,p_purchase_id,p_received_at,v_user,'received');
 for v_line in select * from jsonb_array_elements(p_lines) loop
  select * into v_purchase_line from public.purchase_lines where id=(v_line->>'purchase_line_id')::uuid and purchase_id=p_purchase_id;if not found then raise exception 'Purchase line not found: %',v_line->>'purchase_line_id';end if;
  v_received:=greatest(0,coalesce((v_line->>'received_quantity')::numeric,0));v_accepted:=greatest(0,coalesce((v_line->>'accepted_quantity')::numeric,0));v_rejected:=greatest(0,coalesce((v_line->>'rejected_quantity')::numeric,v_received-v_accepted));v_replacement:=greatest(0,coalesce((v_line->>'replacement_quantity')::numeric,0));if v_received<v_accepted+v_rejected then raise exception 'Accepted + rejected exceeds received for purchase line %',v_purchase_line.id;end if;
  insert into public.purchase_receipt_lines(receipt_id,purchase_line_id,received_quantity,accepted_quantity,rejected_quantity,replacement_quantity,unit_id,received_batch_date,expiry_date,best_before_date,notes) values(v_receipt_id,v_purchase_line.id,v_received,v_accepted,v_rejected,v_replacement,v_purchase_line.unit_id,coalesce((v_line->>'received_batch_date')::date,p_received_at::date),(v_line->>'expiry_date')::date,(v_line->>'best_before_date')::date,v_line->>'notes');
  if v_accepted>0 then v_batch_id:=gen_random_uuid();insert into public.inventory_batches(id,item_id,source_type,source_id,source_line_id,batch_date,quantity_received,quantity_remaining,unit_id,unit_cost,expiry_date,best_before_date,status) values(v_batch_id,v_purchase_line.item_id,'purchase_receipt',v_receipt_id,v_purchase_line.id,p_received_at::date,v_accepted,v_accepted,v_purchase_line.unit_id,v_purchase_line.unit_rate,(v_line->>'expiry_date')::date,(v_line->>'best_before_date')::date,'active');insert into public.inventory_transactions(item_id,batch_id,transaction_type,quantity,unit_id,occurred_at,reference_type,reference_id,reference_line_id,unit_cost,notes,created_by) values(v_purchase_line.item_id,v_batch_id,'purchase_receipt',v_accepted,v_purchase_line.unit_id,p_received_at,'purchase_receipt',v_receipt_id,v_purchase_line.id,v_purchase_line.unit_rate,'Accepted purchase receipt',v_user);end if;
  v_count:=v_count+1;if v_accepted<v_purchase_line.billed_quantity then v_status:='partial_returned';end if;v_outcome:=case when v_accepted=0 then 'returned' when v_accepted<v_received then 'partially_accepted' else 'accepted' end;insert into public.purchase_inspections(receipt_id,purchase_line_id,inspected_at,inspected_by,outcome,notes) values(v_receipt_id,v_purchase_line.id,p_received_at,v_user,v_outcome,v_line->>'inspection_notes');
 end loop;
 if v_count=0 then raise exception 'At least one receipt line is required';end if;update public.purchase_receipts set status='inspected' where id=v_receipt_id;update public.purchases set workflow_status=v_status,updated_at=now() where id=p_purchase_id;perform public.record_audit_event('purchase.received','purchase',p_purchase_id,jsonb_build_object('receipt_id',v_receipt_id,'lines',v_count),'application');return jsonb_build_object('receipt_id',v_receipt_id,'purchase_id',p_purchase_id,'status',v_status);
end; $$;
revoke all on function public.receive_purchase(uuid,jsonb,timestamptz) from public,anon;grant execute on function public.receive_purchase(uuid,jsonb,timestamptz) to authenticated;

create or replace function public.confirm_order_reserve(p_order_id uuid) returns jsonb language plpgsql security invoker set search_path = '' as $$
declare v_user uuid:=auth.uid();r record;v_available numeric;v_reserve numeric;v_shortfall numeric:=0;v_count int:=0;v_status text;
begin
 if v_user is null then raise exception 'Authentication required';end if;select status into v_status from public.orders where id=p_order_id for update;if v_status is null then raise exception 'Order not found';end if;if v_status<>'draft' then raise exception 'Order is already confirmed or progressed';end if;
 for r in select ol.id,ol.item_id,ol.ordered_quantity,ol.unit_id from public.order_lines ol where ol.order_id=p_order_id order by ol.id loop
  select coalesce(current_stock,0)-coalesce(reserved_stock,0) into v_available from public.v_inventory_current where item_id=r.item_id;v_reserve:=greatest(0,least(r.ordered_quantity,coalesce(v_available,0)));
  if v_reserve>0 then insert into public.stock_reservations(order_id,order_line_id,item_id,quantity_reserved,unit_id,status,reserved_at,created_by) values(p_order_id,r.id,r.item_id,v_reserve,r.unit_id,'active',now(),v_user);update public.order_lines set reserved_quantity=coalesce(reserved_quantity,0)+v_reserve,updated_at=now() where id=r.id;end if;
  if v_reserve<r.ordered_quantity then v_shortfall:=v_shortfall+(r.ordered_quantity-v_reserve);end if;v_count:=v_count+1;
 end loop;
 update public.orders set status=case when v_shortfall>0 then 'production_planned' else 'confirmed' end,confirmed_at=now(),confirmed_by=v_user,updated_at=now() where id=p_order_id;perform public.record_audit_event('order.confirmed','order',p_order_id,jsonb_build_object('lines',v_count,'shortfall',v_shortfall),'application');return jsonb_build_object('order_id',p_order_id,'reserved',v_count,'shortfall',v_shortfall,'status',case when v_shortfall>0 then 'production_planned' else 'confirmed' end);
end; $$;
revoke all on function public.confirm_order_reserve(uuid) from public,anon;grant execute on function public.confirm_order_reserve(uuid) to authenticated;

-- Production and dispatch/sale functions are maintained in the matching Phase 4 database migration history.
